James/account abstraction
starknet-io/starknet-docs pull request #101
Opened 2022-11-07 10:07 UTC by JameStark

### Description of the Changes

Account abstraction addition to docs. Enhancement

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2022-11-07 13:02 UTC, stoobie requested changes
I didn't finish the entire review.

In general, you can work on minimalism in your writing. Ask yourself if and how you can simplify sentences. Look for phrases that don't provide benefit, or that you can express in fewer words. E.g. "broadly speaking" can be "generally" or maybe isn't even necessary at all.

2022-11-08 10:09 UTC, JameStark reviewed
> Reviewed 1 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101)* status: 3 of 6 files reviewed, 10 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 4 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101#-NGGYp3EwjDgjyfE2WAY-r3-4:-NGLbCALBUOegUBUOtbg:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L4)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

```suggestion
Starknet has its own account smart contract that you should use as the base/template/whatever for all new account contracts. This contract, combined with the underlying operating system, provides three important features that create a basic account framework from which you can extend:
```
I don't feel like "extend" can stand on its own like this. Or that you "extend an account contract". Is there another word or another way to say this?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 13 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101#-NGGYp3EwjDgjyfE2WAY-r3-13:-NGLblnj9B4syTfttVre:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L13)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Same comment about extend.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 16 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101#-NGHUyvZAxVv0ut8DMrd:-NGHUyvZAxVv0ut8DMre:bjg466r) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L16)):*
> sequencers to charge fair fees for the resources they use. 
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 18 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101#-NGGYp3EwjDgjyfE2WAY-r3-18:-NGHV1bx3Mi0YJaJBH-z:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L18)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

```suggestion
These serve distinct purposes to ensure honest behavior and to provide a mechanism for sequencers to charge fair fees for the resources they use. 
```
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 30 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101#-NGGYp3EwjDgjyfE2WAY-r3-30:-NGHUJa_AWpUAYsOBdy5:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L30)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Can you avoid using the passive voice here? Who pays the fees? Can you say "<entity> pays fees to the sequencer..." Or "The sequencer receives fees..."?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 4 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101#-NGGYp3EwjDgjyfE2WAZ-r3-4:-NGLgD2q30OI30Onm0s0:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L4)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

```
can be thought of
```
This phrase sounds kind of wishy washy. Maybe "is analogous to" or "is similar to"..."can be thought of" sounds ambivalent and ambiguous.

Would it be correct to say:
```
Account abstraction implements a smart contract within a user account.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-08 10:10 UTC, JameStark reviewed
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/101)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-11-16 08:49 UTC, JameStark reviewed
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: all files reviewed, 10 unresolved discussions (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-11-17 08:24 UTC, JameStark reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-11-17 08:29 UTC, JameStark reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: all files reviewed, 10 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 28 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NGGYp3EwjDgjyfE2WAY-r3-28:-NH3gX3E9j2s8CC3fZNn:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L28)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

```suggestion
The underlying Starknet OS, which the sequencer runs, offers a payment mechanism for moving funds and charging fees. This mechanism is deliberately abstracted from the account contract itself to avoid some of the risks to the sequencer executing the transactions.  
```
Avoid using "this" without a noun following it. It's often not 100% clear what "this" refers to. I would say "never", but *this* is something my mother told me not to do. :stuck_out_tongue_winking_eye: 

What kind of risks? Would it be helpful to provide one or two examples?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 6 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NGGYp3EwjDgjyfE2WAZ-r3-6:-NH3gYtv-kiligxB8t-7:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L6)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

"It" refers to the last noun mentioned. Is that what you mean here?

Also, I think this can be significantly more concise. Is there any meaning missing from the following?
```suggestion
You can now program how an account functions. 
```

</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 8 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NGGYp3EwjDgjyfE2WAZ-r3-8:-NH3gZWX8ncohESzJbD8:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L8)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Again, "this" is missing a noun in two instances.

Can you simplify this sentence? It's appropriate for a blog or a book or article, but less so for technical writing.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 10 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NGGYp3EwjDgjyfE2WAZ-r3-10:-NH3gY9G3WkV7qVJxmDP:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/242974b3e15c70c6e13f1500e796ae065b01224b/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L10)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Simplify this sentence.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-17 08:30 UTC, JameStark reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-:-NH3hYLS9-DL8dVrWjQ0:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-11-22 10:14 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: all files reviewed, 46 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 21 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4sYzz-3EJMDuqfVx9:-NHTpK492TJkzlCk43jb:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/nav.adoc#L21)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Sentence case for headings.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 11:09 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 3 of 6 files reviewed, 46 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 7 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4sl9s7xwJiEg4IM-x:-NHTrLRP0D2pE87yQ_xE:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L7)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

1. If you wanted to make this a heading, it could be:

*Examples of progammability*

But because it's not a heading, it should be a full sentence because it's easier for localization using translation software to deal with complete sentences than sentence fragments.
2. I don't understand what "programmability" means.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 13 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4uTTTDiX95HD1gJja:-NHTrqss2392gvF5IY6C:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L13)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

This would be good as a description list.

Social recovery:: a process where if you lose your wallet...
Signature abstraction:: You can choose...
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 13 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4ul_v-zuMlJUJSW5v:-NHTs35mDEb2BxUtSc1N:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L13)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Avoid "allows". It's kind of wishy-washy. I usually rewrite it as "You can". If focus needs to stay on the thing, then I was taught to use "Xyz enables" instead of "allows". However, if "allows" is the most accurate, then you can use it.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 13 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4woww7URhbpvA9Xr_:-NHTsMjsBUgfHEJREf2f:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L13)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

"For example" should be the beginning of a sentence.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 18 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4xggeC1zXLW3s5gDg:-NHTsP_GEFg-MenxyDEr:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L18)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I don't see any benefit to this. Just start the sentence with "An account is"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 20 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4xxaL9_29jSaZKO2D:-NHTsWUo5S-tgFGRUd7b:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L20)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

You need an account to
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 20 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4y62l3L90YKSt16zq:-NHTsfYyBJFyuz8k7FGd:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L20)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Simplify and make more relevant to your reader.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 25 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4yZIu0I0cECHm0yJU:-NHTsopb8kCIfjV5tMbw:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L25)):*
> ```AsciiDoc
> == Ethereum Account Structure
> 
> Within Ethereum, individual user accounts are known as Externally Owned Accounts (EOAs), an implementation where you are directly responsible for the storage of your own private keys. 
> ```

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 31 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4zoJs-x70ZmHod1Am:-NHTtCsTCdCImsO-YN15:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L31)):*
> ```AsciiDoc
> Although this is theoretically a secure method of account management, in practice it has some drawbacks such as having a large emphasis on seed phrase security and limited flexibility surrounding wallet functionality.  
> 
> EIP 4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated Smart Contract on the Ethereum network. This is in the interest of increased flexibility and usability. It allows you to add custom logic on top of the basic account functionality provided. 
> ```

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 31 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4zy4q7kxyngA1n_a9:-NHTtS7E1efcZY8OAJyD:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L31)):*
> ```AsciiDoc
> Although this is theoretically a secure method of account management, in practice it has some drawbacks such as having a large emphasis on seed phrase security and limited flexibility surrounding wallet functionality.  
> 
> EIP 4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated Smart Contract on the Ethereum network. This is in the interest of increased flexibility and usability. It allows you to add custom logic on top of the basic account functionality provided. 
> ```

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 31 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH5-9iW02tzjiFKZrzT:-NHTtcQm86n0nI2enCIa:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L31)):*
> ```AsciiDoc
> Although this is theoretically a secure method of account management, in practice it has some drawbacks such as having a large emphasis on seed phrase security and limited flexibility surrounding wallet functionality.  [...]

2022-11-22 11:22 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 2 of 6 files reviewed, 46 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 4 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH52OEW6fajZ-r0-h_6:-NHU19y2B-p7cA_cmIVY:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L4)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Always use present tense unless you have not choice.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 5 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH530m3AAw8qTzfK-JR:-NHU1aMM7reVuxZUH8Yt:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L5)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

What are the actual function names?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 8 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH535Z72yBsn0ukON1U:-NHU1g-13BZ91FTLoo0O:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L8)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I don't know what this means.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 10 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH53Dzo2S8H2Wa6BBEX:-NHU1nUX8MlC71lom6fZ:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L10)):*
> ```AsciiDoc
> These should be your focus when extending account functionality.
> 
> Separating validate and execute ensures that sequencers are guaranteed payment for work completedand are not susceptible to Denial of Dervice (DoS) attacks.
> ```

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 13 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH53dab056vrC9lNn4_:-NHU1yXI8anjNpQyMJUO:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L13)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Present it as it is in code.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 19 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH54_nQAdJjWX0_6066:-NHU2Oub0PQdmhOUsLH2:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L19)):*
> ```AsciiDoc
> Without this mechanism, a forged transaction could result in the sequencer taking a fee and charging you unfairly. In short, validate ensures that the sequencer can only charge for valid transactions. 
> 
> In addition to this, having a separate validate function allows the sequencer to quickly and efficiently select valid transactions from the Starknet mempool. This in turn ensures that sequencers can charge more accurately compared to a system where validate and execute functions are bound together. 
> ```

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 24 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH55Scb7FTdevnuRtlV:-NHU36kM8zcIuGrZiKHn:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L24)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Rewrite to avoid the passive voice.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 29 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH55Z8dCtz9H3VhX5rf:-NHU3V1eDPKfC77JkV9k:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L29)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Use present tense.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 34 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH55pK13wR4IYgXH6Ip:-NHU3ZDR8ccCWhqQYsKI:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L34)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Avoid future tense and passive voice.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 36 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH55ybl7ryt3SciLnRD:-NHU3lDG6uOr2lpo72eV:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L36)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Avoid passive voice and future tense
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 11:29 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 2 of 6 files reviewed, 46 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 31 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4zCDJEuc8GkDkwBSF:-NHU5M_n5xNE2_F2Hqr8:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L31)):*
> ```AsciiDoc
> Although this is theoretically a secure method of account management, in practice it has some drawbacks such as having a large emphasis on seed phrase security and limited flexibility surrounding wallet functionality.  
> 
> EIP 4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated Smart Contract on the Ethereum network. This is in the interest of increased flexibility and usability. It allows you to add custom logic on top of the basic account functionality provided. 
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 11:36 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 2 of 6 files reviewed, 46 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 3 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4toFmEtJz1iVMdqJ1:-NHU5yK_1F8cEfybFTrE:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L3)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

What do you mean by "the protocol layer"?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 27 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4yiCME05-OaHJID5g:-NHU7-3CArOE7C5hqin0:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L27)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

too wordy.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 29 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH4zJDcDaDLgoQv01u1:-NHU6jhd2GL041fcqGm_:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L29)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

What do you mean by "limited flexibility surrounding wallet functionality"?
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 31 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH5--fLC1QBQZPVjkce:-NHU6n-B1EJoF42q-gwK:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L31)):*
> ```AsciiDoc
> Although this is theoretically a secure method of account management, in practice it has some drawbacks such as having a large emphasis on seed phrase security and limited flexibility surrounding wallet functionality.  
> 
> EIP 4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated Smart Contract on the Ethereum network. This is in the interest of increased flexibility and usability. It allows you to add custom logic on top of the basic account functionality provided. 
> ```

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 4 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NH52Yb09dwGxrCxsRxQ:-NHU5aY3BQA08htPmthW:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7a6d9f3585b2bed1ee86897d8eae7c9acd9713f8/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L4)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Well written sentence, but can you simplify it? It should be easier to parse. Like:

StarkNet's account smart contract includes the following two functions, which account transactions call:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 11:36 UTC, JameStark reviewed
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: all files reviewed, 46 unresolved discussions (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-11-23 08:31 UTC, stoobie requested changes
Search and replace "will" with present tense throughout. 

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-:-NHYa9iP3VRTW0CDKqL4:bmdru3l)* status: 1 of 10 files reviewed, 29 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 4 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHUx2tC6LpPygpJK_bY:-NHUx2tC6LpPygpJK_bZ:b1yjhq3) ([raw file](https://github.com/starknet-io/starknet-docs/blob/68671da8e1eb4688ed734200e0d20bd341052a6d/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L4)):*
> ```AsciiDoc
> = Starknet's approach to account management
> 
> StarkNet has its own account smart contract that all new account contracts should build upon. The StarkNet account contract combined with the underlying operating system provides three important features that create a basic account structure:
> ```

Why not just say "you should use..."?

"all new account contracts should build upon" just sounds less clear and direct.



_Code quote:_
```AsciiDoc
all new account contracts should build upon
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc` line 34 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHUxt9J-mMRmY2bbKoB:-NHUxt9K1tMniT4wxPjf:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/68671da8e1eb4688ed734200e0d20bd341052a6d/components/StarkNet/modules/develop/pages/Account_Abstraction/approach.adoc#L34)):*
> ```AsciiDoc
> == A payment mechanism
> 
> The underlying Starknet OS run by the sequencer offers a payment mechanism for moving funds and charging fees. 
> ```





_Suggestion:_
```AsciiDoc
Starknet OS, run by the sequencer, offers
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 12 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHUyf2Y12Je6qLJtIj8:-NHUyf2Y12Je6qLJtIj9:b-u35v1w) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L12)):*
> ```AsciiDoc
> == What is an account?
> 
> An account is the mechanism by which you manage account balances and account state on the blockchain. 
> ```

This sound like a circular definition: an account...manage account balances...

If i don't already know what an account is, how will I know what an account balance or account state is?



_Code quote:_
```AsciiDoc
n account is the mechanism by which you manage account balances and account state on the blockchain.
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 23 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYSqtx1VHor_iNELvJ:-NHYSqtx1VHor_iNELvK:b-i4t9qc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L23)):*
> ```AsciiDoc
> Although this is theoretically a secure method of account management, in practice it has some drawbacks, such as requiring you to keep your seed phrase secure yet accessible to you, and limited flexibility surrounding wallet functionality.
> 
> EIP-4337, a governance proposal for Ethereum outlines account abstraction whereby all accounts are managed via a dedicated smart contract on the Ethereum network, as a way to increase flexibility and usability. You can add custom logic on top of the basic account functionality provided. 
> ```

The first time you use this new term, good to emphasize it with italics (we need to create a conventions table)



_Suggestion:_
```AsciiDoc
 _account abstraction_,
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 30 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYXdVy12nerSSVrThl:-NHYXdVy12nerSSVrThm:b-75yzbm) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L30)):*
> ```AsciiDoc
> Starknet's account type is based on Ethereum's EIP-4337, where instead of EOAs, the account type uses smart contracts and is almost entirely implementation-agnostic. 
> 
> Through the use of smart contracts, you are provided with complete flexibility within your account implementation.
> ```

Suggestion:

Smart contracts give you complete flexibility when implementing your account.



_Code quote:_
```AsciiDoc
Through the use of smart contracts, you are provided with complete flexibility within your account implementation.
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 32 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYY7zQ-bi3W9k8IoeW:-NHYY7zQ-bi3W9k8IoeX:bqbm1w9) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L32)):*
> ```AsciiDoc
> Through the use of smart contracts, you are provided with complete flexibility within your account implementation.
> 
> This method of account implementation is more broadly known as account abstraction.
> ```

You introduce the term above, why repeat it here?

And again, something about the term "more broadly known as" rubs me the wrong way.



_Code quote:_
```AsciiDoc
This method of account implementation is more broadly known as account abstraction.
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 37 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYYSmr2poUO2tvpuwj:-NHYYSmr2poUO2tvpuwk:bl67cqj) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L37)):*
> ```AsciiDoc
> == Examples of customizing account functionality
> 
> Two examples of how you might program an account to function using account abstraction are:
> ```

Suggestion: "The following examples demonstrate/illustrate use cases for account abstraction:"

I try to stay away from stating the numbers of items in lists. It's obvious there's two examples, and if you add another one later on, then it's one less thing you have to update. Just a rule of thumb.



_Code quote:_
```AsciiDoc
Two examples of how you might program an account to function using account abstraction are:
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 4 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYZ9WtDmiwu6XK_b2f:-NHYZ9WtDmiwu6XK_b2g:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/simplified_transaction_flow.adoc#L4)):*
> ```AsciiDoc
> = Simplified transaction flow
> 
> The key stages of transaction lifetime are:
> ```





_Suggestion:_
```AsciiDoc
The key stages of a transaction's lifetime are:
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYZHz29FS1OzmZ57sO:-NHYZHz35B_yWIkaflrm:br8i9cd) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
> ```AsciiDoc
> The key stages of transaction lifetime are:
> 
> .   A new transaction is sent to the mempool with a nonce
> ```

There are complete sentences. Add a period at the end of each sentence.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` [...]

2022-11-23 08:37 UTC, stoobie requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 1 of 10 files reviewed, 14 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc` line 26 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYbvxF5VWTQQFdjvkD:-NHYbvxF5VWTQQFdjvkE:bl3gwu5) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/validate_and_execute.adoc#L26)):*
> ```AsciiDoc
> == Invalid transactions
> 
> When the `validate` function returns invalid, no fee will be taken from the account in question.
> ```

Is the return value actually `invalid`? Or is it `1` or something else? Either use the actual value, or say something more general like "when the the function returns an error" or "when the transaction is invalid"

Also, don't use "will" here.

Also, there's still passive voice here. Not the end of the world, but I think you can avoid it here.



_Suggestion:_
```AsciiDoc
When the `validate` function returns `invalid`, no fee will be taken from the account in question.
```


<!-- Sent from Reviewable.io -->

2022-12-01 08:49 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/101)* status: 1 of 10 files reviewed, 25 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 4 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8NhuQ4wtmd2Ga4DLE:-NIBoM1w30FFYS26nio_:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I would move this to a new section: "What is account abstraction?", below "Ethereum Account Structure?"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 4 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8OIyIDBXjAnzRmpvL:-NIBodzIAeKvQjgsHtmI:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I would phrase this differently: 

The idea behind account abstraction is to allow more flexibility in the management of accounts rather than have their behavior determined at the protocol level. This can be achieved by introducing account contracts - smart contracts with programmable logic that determine the user's account.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 6 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8FGaD-mUp9reb-fyP:-NIBonR58N0EU06qbwRB:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L6)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

your
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 6 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8FHoxBJfPjL--5IAl:-NIBpaTq9vo4m5vlSKs5:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L6)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I would add something here (feel free to rephrase / discuss if you disagree):

Using account abstraction, you can now program how your account functions. For example, you can: 

- Determine what it means for a signature to be valid or what contracts your account is allowed to interact with. This is known as "signature abstraction"
- Design your own replay protection mechanism and allow sending multiple uncoupled transactions in parallel. Compare this to the sequential nonce solution used in Ethereum, which results in transactions being inherently sequential, i.e., even if one wants to send two transactions in parallel, he must wait for some confirmation on the first before sending the second. Otherwise, the second transaction may be rejected due to an invalid nonce. With account abstraction, one can discuss different solutions that bypass the need for a sequential nonce. This is known as "nonce abstraction"
- Pay transaction fees in different tokens - this is sometimes known as "fee abstraction"

Today, StarkNet offers signature abstraction. In the future, we will enrich the current account abstraction design (see e.g. the paymaster proposal [add link] for fee abstraction).


</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 12 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHUyf2Y12Je6qLJtIj8:-NIBq3yP2g677k3jr1D_:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L12)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I agree. I suggest something in the spirit of:

An account is a user's representation on-chain and his way of interacting with the blockchain. Through an account, a user may send transactions and interact with other contracts. To "own" an on-chain assert (e.g. ERC20 token or an NFT), it has to be associated with my account address.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 14 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8H8by7OQ8oOM4r6Ea:-NIBqjdG2P-mDnnxy-ME:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L14)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I would remove the first part of the sentence as it's a specific example of one transaction and replace "state-based system" with blockchain.
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
Within Ethereum individual user accounts are known as Externally Owned Accounts (EOAs). You are directly responsible for the storage of your own private keys.
```
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 19 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8Ig4g8pGTxHEPRV1o:-NIBr2Y25D81bG22gcgE:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

IMO this is a very specific property of an EOA to mention this early. I would continue with the definition:

EOAs differ from smart contracts in that they are not controlled by code. An EOA is determined by a pair of (private, public) keys. The account's address is determined from those keys, and only by possessing the private key can we initiate transactions from an account. While Ethereum contracts are "passive", i.e., they can only mutate if they were called inside a transaction, EOAs can initiate transactions.

While simple, EOAs have a major drawback: there's no flexibility in the account behavior. The Ethereum protocol dictates what it means for a transaction initiated by an EOA to be valid (the signature scheme is fixed). In particular, control over the public key gives complete control over the account.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 23 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NHYSqtx1VHor_iNELvJ:-NIBrEEV4xB0ghebg-YK:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L23)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

The first time you use this new term, good to emphasize it with italics (we need to create a conventions table)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc` line 23 at r11](https://reviewable.io/reviews/starknet-io/starknet-docs/101#-NI8MOUhAUiw-xGyVNqo:-NIBrLGCCbpiHMhsyXkp:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4cf6b1adcb0d92efd0574b71e421363e8cb08d67/components/StarkNet/modules/develop/pages/Account_Abstraction/introduction.adoc#L23)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><bloc [...]

2022-12-14 08:18 UTC, closed without merging