Update version_notes.adoc with v0.13 versions on testnets
starknet-io/starknet-docs pull request #1023
Opened 2023-12-13 11:24 UTC by odednaor

### Description of the Changes

Release notes of Starknet v0.13, and update versions tables on Starknet, Cairo, and Sierra version numbers.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2023-12-13 11:41 UTC, odednaor commented
@stoobie What should we do with the v0.13 release notes on the [upcoming versions page](https://starknet-io.github.io/starknet-docs/pr-1023/documentation/starknet_versions/version_notes/) while mainnet is not yet upgraded to v0.13?

2023-12-13 14:23 UTC, ArielElp reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1023)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @odednaor and @stoobie)

___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 32 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlXwzm0C8iTasel9UKF:-NlXwzm0C8iTasel9UKG:b-vfgi4k) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e73dc92987760c6fc043724a62632b6f1fa364d0/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L32)):*
> ```AsciiDoc
> ** Fee payment in STRK
> ** Reserved fields for future features, such as volition and payment master
> * `get_block` API: Rename the `gas_price` field to `eth_l1_gas_price` and add a new field `strk_l1_gas_price` (this applies to old blocks as well)
> ```

Replace this point with a link to v0.6.0 spec https://github.com/starkware-libs/starknet-specs/releases/tag/v0.6.0
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 33 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYYTksA66UdssvT3PS:-NlYYTksA66UdssvT3PT:bbtzbi0) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e73dc92987760c6fc043724a62632b6f1fa364d0/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L33)):*
> ```AsciiDoc
> ** Reserved fields for future features, such as volition and payment master
> * `get_block` API: Rename the `gas_price` field to `eth_l1_gas_price` and add a new field `strk_l1_gas_price` (this applies to old blocks as well)
> * Update Sierra version used in Starknet to `1.4.0` (introduced in crate version `v2.4.0` of the cairo package)
> ```

replace this with a link here https://community.starknet.io/t/cairo-v2-4-0-is-out/109275
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYYeqVCSLJpqrNb9As:-NlYYeqW7Wlv8q-jI7Sy:b-owjsbz) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e73dc92987760c6fc043724a62632b6f1fa364d0/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L35)):*
> ```AsciiDoc
> * Update Sierra version used in Starknet to `1.4.0` (introduced in crate version `v2.4.0` of the cairo package)
> * Improved performance of `secp256k1_mul` and `secp256r1_mul` syscalls
> ```

we need a another bullet point about cost reduction: computation cost is reduced by roughly 2x (cairo steps and builtins), DA cost is reduced by roughly 10%.


<!-- Sent from Reviewable.io -->

2023-12-13 14:55 UTC, stoobie requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1023)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ArielElp and @odednaor)

___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYYeqVCSLJpqrNb9As:-NlYfGXR9tP09BjIx0tJ:b-83330m) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e73dc92987760c6fc043724a62632b6f1fa364d0/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L35)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

we need a another bullet point about cost reduction: computation cost is reduced by roughly 2x (cairo steps and builtins), DA cost is reduced by roughly 10%.
</blockquote></details>

PTAL.
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 32 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYdMWeE7lUN8wTZztX:-NlYdMWeE7lUN8wTZztY:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4ddaae955d2ba31b8dedc90838372cac485e495c/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L32)):*
> ```AsciiDoc
> ** Fee payment in STRK
> ** Reserved fields for future features, such as volition and payment master
> * `get_block` API: Rename the `gas_price` field to `eth_l1_gas_price` and add a new field `strk_l1_gas_price` (this applies to old blocks as well)
> ```





_Suggestion:_
```AsciiDoc
`get_block` API: The `gas_price` field is replaced by the `eth_l1_gas_price` and `strk_l1_gas_price` fields. This change applies also to existing blocks. For more information on the new fields, see the link:https://github.com/starkware-libs/starknet-specs/releases/tag/v0.6.0[JSON RPC API Spec on Github]
```
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 33 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYe91SEox55DzHU_Q6:-NlYe91SEox55DzHU_Q7:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4ddaae955d2ba31b8dedc90838372cac485e495c/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L33)):*
> ```AsciiDoc
> ** Reserved fields for future features, such as volition and payment master
> * `get_block` API: Rename the `gas_price` field to `eth_l1_gas_price` and add a new field `strk_l1_gas_price` (this applies to old blocks as well)
> * Update Sierra version used in Starknet to `1.4.0` (introduced in crate version `v2.4.0` of the cairo package)
> ```





_Suggestion:_
```AsciiDoc
* Sierra v1.4.0. This new version of Sierra is part of Crate v2.4.0, in the Cairo 2.4.0 package.
```
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 34 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYebPP-729Bl_lX5FD:-NlYebPP-729Bl_lX5FE:b-ahv4n1) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4ddaae955d2ba31b8dedc90838372cac485e495c/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L34)):*
> ```AsciiDoc
> * `get_block` API: Rename the `gas_price` field to `eth_l1_gas_price` and add a new field `strk_l1_gas_price` (this applies to old blocks as well)
> * Update Sierra version used in Starknet to `1.4.0` (introduced in crate version `v2.4.0` of the cairo package)
> * Improved performance of `secp256k1_mul` and `secp256r1_mul` syscalls
> ```

We don't document these syscalls. Should we?
___
*[`components/Starknet/modules/starknet_versions/pages/version_notes.adoc` line 34 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1023#-NlYep5GC0r2sDXgy5Cn:-NlYep5GC0r2sDXgy5Co:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/4ddaae955d2ba31b8dedc90838372cac485e495c/components/Starknet/modules/starknet_versions/pages/version_notes.adoc#L34)):*
> ```AsciiDoc
> * `get_block` API: Rename the `gas_price` field to `eth_l1_gas_price` and add a new field `strk_l1_gas_price` (this applies to old blocks as well)
> * Update Sierra version used in Starknet to `1.4.0` (introduced in crate version `v2.4.0` of the cairo package)
> * Improved performance of `secp256k1_mul` and `secp256r1_mul` syscalls
> ```





_Suggestion:_
```AsciiDoc
* Improved performance of `secp256k1_mul` and `secp256r1_mul` syscalls
* Computation cost is reduced approximately 200% as a result of reduced Cairo steps and increased use of builtins. L1 data availability cost is reduced by approximtately 10%.
```


<!-- Sent from Reviewable.io -->

2023-12-13 14:58 UTC, stoobie requested changes
@odednaor I added some comments and suggestions in Reviewable.

2023-12-14 04:49 UTC, stoobie commented
> @stoobie What should we do with the v0.13 release notes on the [upcoming versions page](https://starknet-io.github.io/starknet-docs/pr-1023/documentation/starknet_versions/version_notes/) while mainnet is not yet upgraded to v0.13?

Well, the info on that page is more detailed than the info in this PR. I thought to just move that info into the Release notes and remove that page for now. We clearly state the status on testnet and Mainnet.

2023-12-14 13:07 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Add transaction v3:
```suggestion
Starknet 0.13.0 includes the following changes:

* v3 transactions, including:
```

2023-12-14 13:07 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +** Reserved fields for future features, such as volition and payment master
```suggestion
** Reserved fields for future features, such as Volition and payment master
```

2023-12-14 13:15 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Computation cost is reduced approximately 200% as a result of reduced Cairo steps and increased use of builtins. L1 data availability cost is reduced by approximtately 10%.
```suggestion
* Computation cost is reduced by approximately 200% as a result of reduced Cairo steps and increased use of builtins. L1 data availability cost is reduced by approximtately 10%.
```

2023-12-14 13:23 UTC, merged