Add  Table and  fix small issue
starknet-io/starknet-docs pull request #1057
Opened 2023-12-30 05:57 UTC by hardiktheprogrammer

### Description of the Changes

Add table in bridged tokens and fix small issue

### PR Preview URL

### Check List

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2023-12-30 05:59 UTC, hardiktheprogrammer commented
@stoobie  👀

2023-12-31 07:54 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/pathfinder_versions.adoc
> +this only applies if you are building from source. This does not impact docker users.
```suggestion
This only applies if you are building from source. This does not impact docker users.
```

2023-12-31 08:09 UTC, stoobie requested changes
A few comments. Additionally, since I added you as a collaborator, you can add branches directly to the starknet-io instead of from your fork. That way you'll generate a preview so you can see what your changes will look like.

2023-12-31 08:09 UTC, stoobie commented on components/Starknet/modules/tools/pages/bridged_tokens.adoc
> +*The tokens that are currently bridged to Starknet are listed in the following `.json` files:*
Avoid formatting sentences with bold unless it's really necessary. We want to preserve markup language semantics, and using hard-coded formatting interferes with the page semantics.

If you need to make a sentence bold as a caption or title without adding structure via an actual heading, AsciiDoc provides dot headings:

`.A dot followed by text will be bold`

I use this syntax for the word *Procedure* to visually set off the beginning of a procedure.

In this case, I suggest keeping this sentence non-bold, and adding a title to the table by putting a doc heading with the title text on the line immediately preceding the beginning of the table.

2023-12-31 08:09 UTC, stoobie commented on components/Starknet/modules/tools/pages/bridged_tokens.adoc
> +*Each token has the following parameters:*
```suggestion
.Token parameters
```

2023-12-31 08:09 UTC, stoobie commented on components/Starknet/modules/tools/pages/starkgate-cancelling a deposit.adoc
> +* When StarkGate receives the cancellation request, a counter begins to count five days.
General rule: Never have a single list item. If you have one bullet, you need at least one more. If you only have on item, don't use a bullet.

Treat bullets and numbers as structural, not as formatting.

2023-12-31 09:11 UTC, stoobie commented
@hardiktheprogrammer 
The default branch for this repo is now `main` instead of `master`. [Please follow these steps to update your local repos to use main instead of master from now on.](https://github.com/starknet-io/starknet-docs/discussions/964#discussioncomment-7982322)

2024-03-11 08:02 UTC, stoobie commented
@hardiktheprogrammer Any update on this?

2024-03-18 09:04 UTC, stoobie commented
@hardiktheprogrammer I'm closing this due to inactivity. Please feel free to repoen when you have time.

2024-03-18 09:04 UTC, closed without merging