Update version_notes.adoc with 0.13.1 release notes
starknet-io/starknet-docs pull request #1160
Opened 2024-03-03 12:50 UTC by odednaor

### Description of the Changes

Release notes taken from https://github.com/starkware-libs/cairo-lang/releases/tag/v0.13.1a0.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against main branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2024-03-03 15:37 UTC, stoobie requested changes
Several questions and suggestions.

2024-03-03 15:37 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* *Cheaper data availability:* Starknet uses link:https://eips.ethereum.org/EIPS/eip-4844[EIP-4844].
Why is this section not considered _Technical changes_?

2024-03-03 15:37 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Time-related syscalls when called from account contract's `__validate__` function:
What about validate_deploy and validate_declare?

2024-03-03 15:37 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* *Optimization:* Load only the used functions in a contract into memory when generating the proof
Is this a sequencer change? Or something else? Please specify.

2024-03-03 15:37 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Add `starknet-compiled-class-hash` command
Add this command to what?

2024-03-03 15:37 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +** `eth_l1_gas_price` and `strk_l1_gas_price` were replaced, and the information now contains the data gas price (EIP 4844) in addition to the regular gas price
```suggestion
** `eth_l1_gas_price` and `strk_l1_gas_price` were replaced, and the information now contains the data gas price (EIP-4844) in addition to the regular gas price
```

2024-03-03 15:37 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Starknet now supports multiple L1 providers.
```suggestion
Starknet now supports multiple L1 providers.
```
One item doesn't get a bullet. Only two or more items.

2024-03-04 07:50 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Time-related syscalls when called from account contract's `__validate__` function:
```suggestion
* Time-related syscalls when called from an account contract's `__validate__` function:
```

2024-03-04 07:50 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* *Optimization:* Load only the used functions in a contract into memory when generating the proof
```suggestion
* *Optimization:* Load only the used functions in a contract into memory when generating the proof.
```

2024-03-04 07:51 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Add `starknet-compiled-class-hash` command
```suggestion
* Add `starknet-compiled-class-hash` command.
```

2024-03-04 07:52 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +November
```suggestion
```

2024-03-04 08:10 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +=== New features and enhancements
```suggestion
=== New features and enhancements

```

2024-03-04 08:12 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +=== New features and enhancements
```suggestion
[discrete]
=== New features and enhancements
```

2024-03-04 08:15 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* *Optimization:* Load only the used functions in a contract into memory when generating the proof.
```suggestion
* *Optimization:* Load into memory only the functions in a contract that are actually used when generating the proof.
```

2024-03-04 08:18 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Add `starknet-compiled-class-hash` command.
@ArielElp Add it to what?

2024-03-04 08:19 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Time-related syscalls when called from an account contract's `__validate__` function:
Does this also apply to `__validate_declare__` and `__validate_deploy__`?

2024-03-04 08:40 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Time-related syscalls when called from an account contract's `__validate__` function:
```suggestion
* Time-related syscalls when called from an account contract's `+__validate__+` function:
```

2024-03-04 10:44 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +=== Technical changes:
```suggestion
=== Infrastructure updates
```

2024-03-04 10:45 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Add `starknet-compiled-class-hash` command.
I'm removing this line. Lior explained that this is something specific to cairo-lang that he added to the cairo-lang repo, but it is not useful here.

2024-03-04 15:05 UTC, stoobie commented on components/Starknet/modules/starknet_versions/pages/version_notes.adoc
> +* Add `starknet-compiled-class-hash` command
Lior explained that this is a helper utility for CairoZero, so I removed this.

2024-03-05 09:05 UTC, iliav-starkware commented
LGTM

2024-03-05 09:40 UTC, stoobie approved these changes

2024-03-05 09:42 UTC, iliav-starkware approved these changes

2024-03-05 10:06 UTC, merged