Docs(quick start): Add Tutorial using Starknet devnet and Starknet foundry
starknet-io/starknet-docs pull request #1288
Opened 2024-06-08 03:54 UTC by gianalarcon

### Description of the Changes

Add tutorial of how declare, deploy and interact with a sample smart contract using Starknet devnet.

Following migration of Starknet book. Full issue [here](https://github.com/starknet-edu/starknetbook/issues/341)
 
 I suggest to land this tutorial at the end of `Quick start` section.

### Check List

- [x] Changes have been done against main branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`
- [x] Update/enhance general `Quick Start` section in order this PR make sense.

**This PR depends on the following [PR-24](https://github.com/starknet-io/docs-common-content/pull/24)**

@omarespejel Please have a look here. Thanks
@stoobie I would like your feedback here as well. Thanks

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1191)

2024-07-10 12:54 UTC, stoobie commented
@gianalarcon Can you please rebase main on top of this?

2024-07-14 08:00 UTC, amanusk requested changes

2024-07-15 09:43 UTC, gianalarcon commented on components/Starknet/modules/quick-start/pages/starknet-devnet.adoc
> +
Yes, installation process is on another section. Like I mentioned in the description

"This PR depends on the following [#24](https://github.com/starknet-io/docs-common-content/pull/24)"

2024-08-08 06:14 UTC, closed without merging

2024-08-08 06:14 UTC, LandauRaz commented
Added as part of #1332. Thanks for all your help, @gianalarcon!