Update transactions.adoc with txs v3 fee estimation
starknet-io/starknet-docs pull request #1296
Opened 2024-06-16 13:40 UTC by odednaor

### Description of the Changes

Link to the recommended way to translate the response of `starknet_estimateFee` call to the different fields of `resource_bounds` when sending txs v3.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against main branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2024-06-16 16:15 UTC, stoobie approved these changes
LGTM.

2024-06-17 06:27 UTC, odednaor commented
lgtm as well, @ArielElp, please review.

2024-06-25 12:37 UTC, ArielElp requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1296)* status: all files reviewed, 3 unresolved discussions (waiting on @leo-starkware and @odednaor)

___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOED97iHfscrVqnA2:-O0EOED97iHfscrVqnA3:bo58eod) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
> ```AsciiDoc
> == v3 transaction fee estimation
> 
> Estimate the fees of transactions with the `starknet_estimateFee` API call, which is part of the of the Starknet JSON RPC v0.7 and above. For more information see the link:https://github.com/starkware-libs/starknet-specs/blob/v0.7.1/api/starknet_api_openrpc.json#L612[Starknet API JSON RPC specification]. For information on the recommended way to translate the response fields of the call to the fields in `resource_bounds`, see link:https://community.starknet.io/t/starknet-v0-13-1-pre-release-notes/113664#sdkswallets-how-to-use-the-new-fee-estimates-7[How to use the new fee estimates?] on the Starknet community forum.
> ```

Starknet's json RPC v0.7.0 and above.



_Code quote:_
```AsciiDoc
the Starknet JSON RPC v0.7
```
___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOKmeCJbpyAgVVqSe:-O0EOKmeCJbpyAgVVqSf:bx9hov) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
> ```AsciiDoc
> == v3 transaction fee estimation
> 
> Estimate the fees of transactions with the `starknet_estimateFee` API call, which is part of the of the Starknet JSON RPC v0.7 and above. For more information see the link:https://github.com/starkware-libs/starknet-specs/blob/v0.7.1/api/starknet_api_openrpc.json#L612[Starknet API JSON RPC specification]. For information on the recommended way to translate the response fields of the call to the fields in `resource_bounds`, see link:https://community.starknet.io/t/starknet-v0-13-1-pre-release-notes/113664#sdkswallets-how-to-use-the-new-fee-estimates-7[How to use the new fee estimates?] on the Starknet community forum.
> ```

For more information on how to construct the appropriate `resource_bounds` based on the response of `starknet_estimateFee`, see ...



_Code quote:_
```AsciiDoc
or information on the recommended way to translate the response fields of the call to the fields in `resource_bounds`
```
___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOW2Q-zfgEKfe4YeS:-O0EOW2Q-zfgEKfe4YeT:b26n5yf) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
> ```AsciiDoc
> == v3 transaction fee estimation
> 
> Estimate the fees of transactions with the `starknet_estimateFee` API call, which is part of the of the Starknet JSON RPC v0.7 and above. For more information see the link:https://github.com/starkware-libs/starknet-specs/blob/v0.7.1/api/starknet_api_openrpc.json#L612[Starknet API JSON RPC specification]. For information on the recommended way to translate the response fields of the call to the fields in `resource_bounds`, see link:https://community.starknet.io/t/starknet-v0-13-1-pre-release-notes/113664#sdkswallets-how-to-use-the-new-fee-estimates-7[How to use the new fee estimates?] on the Starknet community forum.
> ```

Starknet JSON RPC specification



_Code quote:_
```AsciiDoc
API JSON RPC specification
```


<!-- Sent from Reviewable.io -->

2024-06-26 14:00 UTC, odednaor reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1296)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @leo-starkware)

___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOED97iHfscrVqnA2:-O0Jq7g9A7Gsgi8EX-YQ:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Starknet's json RPC v0.7.0 and above.
</blockquote></details>

Done.
___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOKmeCJbpyAgVVqSe:-O0Jq83qETnE9bb4WDNw:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

For more information on how to construct the appropriate `resource_bounds` based on the response of `starknet_estimateFee`, see ...
</blockquote></details>

Done.
___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOW2Q-zfgEKfe4YeS:-O0Jq8LuBSXzu9IEKTQm:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Starknet JSON RPC specification
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-26 15:11 UTC, stoobie approved these changes

2024-06-26 15:15 UTC, stoobie commented on components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc
> +Estimate the fees of transactions with the `starknet_estimateFee` API call, which is part of Starknet's JSON RPC v0.7.0 and above. For more information, see the link:https://github.com/starkware-libs
JSON RPC is an API format. Referring to Starknet's API as "Starknet's JSON RPC" is grammatically incorrect.

2024-06-26 15:31 UTC, stoobie approved these changes
@odednaor One comment.

2024-06-27 07:05 UTC, odednaor commented
@stoobie, resolved the comment. Please merge.

2024-06-27 10:12 UTC, ArielElp requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1296)* status: all files reviewed, 2 unresolved discussions (waiting on @leo-starkware, @odednaor, and @stoobie)

___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#-O0EOW2Q-zfgEKfe4YeS:-O0OA-IiCdTvuskbbqPP:b2wzr09) ([raw file](https://github.com/starknet-io/starknet-docs/blob/e6c7ff4fdbb2b213e8d9557d7a8ecb6b50771354/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
<details><summary><i>Previously, odednaor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see Starknet API 0.7.0, which is not a term we're using. Starknet JSON-RPC v0.7.0 is more consistent with other references
___
*[`components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc` line 468 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/1296#gh-1655074769:-O0O9qqz6icXH2ckD9wq:b-ajlc84) ([raw file](https://github.com/starknet-io/starknet-docs/blob/33dfbe0eb67e02bdb26854c4581fa0943cf60f16/components/Starknet/modules/architecture-and-concepts/pages/network-architecture/transactions.adoc#L468)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

JSON RPC is an API format. Referring to Starknet's API as "Starknet's JSON RPC" is grammatically incorrect.
</blockquote></details>

Starknet JSON-RPC or Ethereum JSON-RPC are known references. It's true that technically JSON-RPC is an API format, but Starknet JSON-RPC (or Starknet's JSON-RPC) has a clearer meaning to readers.


<!-- Sent from Reviewable.io -->

2024-07-02 15:42 UTC, stoobie approved these changes
LGTM

2024-07-02 15:43 UTC, merged