Update account-functions.adoc with warning of invoke v0 txs to execute
starknet-io/starknet-docs pull request #1298
Opened 2024-06-20 08:07 UTC by odednaor

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against main branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2024-06-20 08:08 UTC, odednaor commented on components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
> +
@stoobie not sure if the warning is in the correct format. Would also be good to link INVOKE v0 to this page: https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v0_deprecated_hash_calculation

2024-06-26 15:02 UTC, stoobie commented on components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
> +== Potential attacks on `+__validate__+`
```suggestion
== Potential attacks on validation functions
```

2024-06-26 15:05 UTC, stoobie commented on components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
> +== Potential attacks on `+__execute__+`
```suggestion
== Potential attacks on the `+__execute__+` function
```

2024-06-26 15:06 UTC, stoobie commented on components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
> +== Ways to mitigate attacks on `+__execute__+`
```suggestion
== Ways to mitigate attacks on the `+__execute__+` function
```

2024-06-26 15:07 UTC, stoobie commented on components/Starknet/modules/architecture-and-concepts/pages/accounts/account-functions.adoc
> +* Account contracts should explicitly assert in the `+__execute__+` function that the sender is 0 (i.e., the sequencer).
```suggestion
* Account contracts should explicitly assert in the `+__execute__+` function that the sender's address is 0, that is, the sender is the sequencer.
```

2024-06-26 15:08 UTC, stoobie requested changes
@odednaor Please see my suggestions

2024-06-27 07:01 UTC, odednaor commented
@ArielElp wanted to rewrite this section.
Waiting for his suggestions.

2024-07-04 11:48 UTC, closed without merging

2024-07-04 11:49 UTC, odednaor commented
Fixed as par of #1302.