Moving reviewed Account Abstraction section to updated menu structure
starknet-io/starknet-docs pull request #133
Opened 2022-11-28 12:16 UTC by JameStark

### Description of the Changes

Account abstraction work was written prior to a restructure of the side nav.

This PR is the same approved work, moving into the new structure.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2022-12-08 15:47 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 3 of 5 files reviewed, 35 unresolved discussions (waiting on @JameStark and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 4 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkS8uF0j7X7rGX8JSC:-NIkS8uF0j7X7rGX8JSD:b-996b29) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L4)):*
> ```AsciiDoc
> = `validate` and `execute`
> 
> StarkNet's account smart contract includes the following two functions, which account transactions call: 
> ```

As we saw, StarkNet's account structure is not completely arbitrary, but must include the following two ...



_Code quote:_
```AsciiDoc
StarkNet's account smart contract includes
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 6 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkSJfu4WFvDvAq00Ft:-NIkSJfu4WFvDvAq00Fu:b-qd8kxh) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L6)):*
> ```AsciiDoc
> StarkNet's account smart contract includes the following two functions, which account transactions call: 
> 
> * `validate`
> ```

add underscores (same for execute?)
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 14 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkSTId0a790DtUJ7CV:-NIkSTId0a790DtUJ7CW:b3prktr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L14)):*
> ```AsciiDoc
> == The `validate` function
> 
> The `validate` function:
> ```

I think that we need to change this section a bit. The primary motivation behind validate is to allow the account to check that a transaction was indeed initiated by the owner. DOS is related to the validate/execute separation, but the validation logic itself is important for the user; without it, incorrectly charging fees is the least of his problems since malicious actors can just take his money.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 16 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkTMsS6vpoXXqMvrix:-NIkTMsS6vpoXXqMvriy:b27wrlo) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L16)):*
> ```AsciiDoc
> The `validate` function:
> 
> *   Ensures that any transaction submitted is genuine and therefore will not take up unjustified resources during the execution process.
> ```

was indeed initiated by the account owner



_Code quote:_
```AsciiDoc
therefore will not take up unjustified resources during the execution process
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 18 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkUJdV0SkO0Zn1ugnU:-NIkUJdV0SkO0Zn1ugnV:b-d7ex7o) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L18)):*
> ```AsciiDoc
> *   Ensures that any transaction submitted is genuine and therefore will not take up unjustified resources during the execution process.
> 
> Without this mechanism, a forged transaction can result in the sequencer taking a fee and charging you unfairly.
> ```

stealing the user's funds



_Code quote:_
```AsciiDoc
the sequencer taking a fee and charging you unfairly
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 19 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkUlCg522AVhO6z3qZ:-NIkUlCg522AVhO6z3q_:be4b68y) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L19)):*
> ```AsciiDoc
> 
> Without this mechanism, a forged transaction can result in the sequencer taking a fee and charging you unfairly.
> In short, `validate` ensures that the sequencer can only charge for valid transactions.
> ```

may only include transactions that were approved by the account owner.



_Code quote:_
```AsciiDoc
can only charge for valid transactions
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 19 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkWEH85mT0sHEN8Whn:-NIkWEH85mT0sHEN8Who:b-np57tt) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L19)):*
> ```AsciiDoc
> 
> Without this mechanism, a forged transaction can result in the sequencer taking a fee and charging you unfairly.
> In short, `validate` ensures that the sequencer can only charge for valid transactions.
> ```

I would add the following:

The arbitrary logic allowed in the validate function gives the account's designer the ability to determine what it means to him for a transaction to be valid. This gives rise to the usage of different signature schemes and other [exotic accounts](link to the subtitle with the facial recognition example from the other page).
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 21 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkYCpw7doUXGw6RJ18:-NIkYCpw7doUXGw6RJ19:b-w87tdp) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L21)):*
> ```AsciiDoc
> In short, `validate` ensures that the sequencer can only charge for valid transactions.
> 
> * Enables the sequencer to quickly and efficiently select valid transactions from the Starknet mempool, ensuring that sequencers can charge more accurately than in a system where `validate` and `execute` functions are bound together.
> ```

This should be removed, it doesn't help charging more accurately (it helps charging, or knowing that you will be able to charge)



_Code quote:_
```AsciiDoc
ensuring that sequencers can charge more accurately
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 21 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkYRzhCHzJYPfKpgCy:-NIkYRzhCHzJYPfKpgCz:b-80iid9) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L21)):*
> ```AsciiDoc
> In short, `validate` ensures that the sequencer can only charge for valid transactions.
> 
> * Enables the sequencer to quickly and efficiently select valid transactions from the Starknet mempool, ensuring that sequencers can charge more accurately than in a system where `validate` and `execute` functions are bound together.
> ```

Let's move this to the beginning, i.e. start with "The separation of the validate and execute functi [...]

2022-12-13 15:15 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 3 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 4 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbS26eASuiC7StPbSp:-NJB-85M8YVVct1CCZ4v:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

inspired by
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 8 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbT2gX5famf-FOAHWD:-NJB-rtB7gxu07WKLg5e:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L8)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that we can remove this. Either that or this sentence should go to the introduction page.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 20 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIcCUpnCY7bHJyaHq0U:-NJB083vDdNCgEab6TjM:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L20)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that we should remove this section. StarkNet does not have its own account smart contract, there's a standard implementation that was written by OZ but you can deviate from it. Maybe I'm missing the motivation for this section.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 29 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbvdnZEHGmoC79Nfim:-NJB0GPdBFMUEZ8jnWPr:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L29)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that this should be the first section
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 31 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbvu2mDIWoxIUCeUE3:-NJB0XGa7LytytUD26mj:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L31)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The functions are the interface (as opposed to "they provide the interface"). I suggest replacing with:

A StarkNet account contract must include the following two functions:
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 33 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbwjQTCPnpHXBi9tzA:-NJB0_JTD6g6eIeThFb2:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L33)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

__validate__
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 34 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbwkwoChDJCx8S91eE:-NJB0_a9ClA_244BCNy1:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L34)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

__execute__
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 36 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbx8Uo3rHmtOOiT9s3:-NJB1deN5Cig54CGKdp5:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L36)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This is too general imo, maybe: "that only the account owner can initiate transactions"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 36 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbxSFE8l6inCyyMFcp:-NJB1y6867TZrfqu7TBi:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L36)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

ensure that they can charge fees for the resources they use
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 39 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIcCqgRClHqiyGrdc3w:-NJB2LZIAfPwDF9pbfwo:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L39)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's rename this section "Replay Protection"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 11:03 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 4 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbS7qJBEp_oMG1k697:-NJFG0K83auxwLsfoYID:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I'm not sure about this sentence. What's "account type" in what sense the account is implementation-agnostic? (it's defined by it)

Maybe consider "where instead of EOAs, users now use smart contract accounts with arbitrary verification logic". 
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 37 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbyU7E7o4BjXbp0xbP:-NJFGPH8BrW5VG2Ua2Jz:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L37)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's add here a reference to the standard:

While not mandatory at the protocol level, a richer standard interface for accounts was developed by the community. This standard was developed by OpenZeppelin, in a close collaboration with wallet teams and other Core StarkNet developers. You can see the IAccount interface here https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/IAccount.cairo.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 45 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIcGanWBQe3JU7Srx2A:-NJFGYL_Agq1vm7aTSRP:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L45)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I'm not sure how nonces help with DOS prevention
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 50 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIcGpyL3mcVRcTmCzWO:-NJFGhBM4b7G1kyryaJF:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L50)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that payment should go into the transaction flow page (i.e. first validate, then execute, then you pay fee).
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 22 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQWtq9Kcpou2hxO9e:-NJB77PWEiRe26mR8eRS:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L22)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's move it to be the first section
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
Using account abstraction, you can now program how your account functions. For example, y
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 25 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQpC21NyxBmdZiT_g:-NJB77oF8VQdxYK3YyHD:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L25)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that everything below this can go to a new third section, "What is account abstraction"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 26 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQmlr3p1Icv6E0Zwt:-NJB6s9PBjCTRYgt5Uoa:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L26)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Using --> With
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 4 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkS8uF0j7X7rGX8JSC:-NJFH-cEBXU4n0KC9S6n:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

As we saw, StarkNet's account structure is not completely arbitrary, but must include the following two ...
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 6 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkSJfu4WFvDvAq00Ft:-NJFIItCDRQVZGyu8Nmg:b-tbg4tf) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L6)):*
> ame for exe


<!-- Sent from Reviewable.io -->

2022-12-14 14:17 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 16 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkTMsS6vpoXXqMvrix:-NJFIVeWA4u2wyTBlAFI:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L16)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

was indeed initiated by the account owner
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 18 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkUJdV0SkO0Zn1ugnU:-NJFIlOb8nW7fQo98pHv:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L18)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

stealing the user's funds
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 19 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkUlCg522AVhO6z3qZ:-NJFIts5DaLO2CiDB8SN:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

may only include transactions that were approved by the account owner.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 26 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImNBvN4iv9yzZpiM3_:-NJFz2oM1waY0Kvj_Yuw:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L26)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

fails
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 31 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImNNR44v8KbqfCXRm3:-NJFzFd-3npNMobYQAEN:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L31)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that we should remove this sentence. The sequencer is already processing when executing validate, so I think it's confusing.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 31 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImNhzQD2cHQBXJYTHn:-NJFzNBa5dgSYdLDDTor:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L31)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's add a few sentences here:

In Ethereum, a transaction is necessary a call to a specific function in a smart contract. With the `execute` abstraction, the account designer controls the flow of the transaction. For example, multicalls can be natively supported in your account, saving the need to send multiple transactions (in practice, this is even harder to manage without multicalls due to nonces).
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 35 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImPsk88C_u8P8dBgfg:-NJFzZ3v4Fs0SFNDeQWQ:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L35)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This isn't clear to me, I suggest replacing with:

A transaction is considered reverted when the `__execute__` function failed. Today, reverted transactions are not included in blocks, but in the future, they will be, and the sequencer will be eligible to charge a fee for the work done up to the point of failure, similarly to Ethereum.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 38 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImPh2t7kpMJdxWC_dY:-NJFzbAPEB3cgtEHP7Is:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L38)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

See above, this is true today but not the desired situation, I think we should make it clear.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 14:40 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 21 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkYCpw7doUXGw6RJ18:-NJG-BtF6QuJvP_H6nYA:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L21)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This should be removed, it doesn't help charging more accurately (it helps charging, or knowing that you will be able to charge)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 21 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkbsMfEhQdQTnrGhLa:-NJG1-Bw4f8quA_4LPeZ:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L21)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I don't think that we need it here
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 21 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkYRzhCHzJYPfKpgCy:-NJG282163SS_O-8-TT3:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L21)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's move this to the beginning, i.e. start with "The separation of the validate and execute function enables..."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 14:55 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 14 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkSTId0a790DtUJ7CV:-NJG5B1xBnZT2WnqWjHt:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L14)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that we need to change this section a bit. The primary motivation behind validate is to allow the account to check that a transaction was indeed initiated by the owner. DOS is related to the validate/execute separation, but the validation logic itself is important for the user; without it, incorrectly charging fees is the least of his problems since malicious actors can just take his money.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 19 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkWEH85mT0sHEN8Whn:-NJG7-2CAkXCxBKMSZWy:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L19)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I would add the following:

The arbitrary logic allowed in the validate function gives the account's designer the ability to determine what it means to him for a transaction to be valid. This gives rise to the usage of different signature schemes and other [exotic accounts](link to the subtitle with the facial recognition example from the other page).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 15:15 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 42 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIcEKIvEXon8HE20QjE:-NJGC8wyBeRl0R5EUAxz:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L42)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

An alternative formulation for this section, let me know if this sounds reasonable:

In StarkNet, similarly to Ethereum, every contract has a nonce. This nonce is sequential; when a transaction is sent from an account, its nonce must match the account's nonce, and it's incremented after the transaction is executed (whether or not it was reverted). Note that, similarly to Ethereum, only the nonce of account contracts (that is, those adhering to the above structure) can be non-zero.

A nonce serves two important roles:
- It guarantees transaction hash uniqueness (this is important for good UX)
- It provides replay protection to the account (since the signature refers to a particular nonce, the transaction can't be replayed by a malicious party)

As seen above, StarkNet currently determines the nonce structure (sequential) at the protocol level. In the future, we may consider a more flexible design, extending account abstraction to nonce management (what we previously referred to as "nonce abstraction").
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-14 15:31 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 35 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 22 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkc-lc4CkV3iH1jacE:-NJGFr256K4Fktc0Fxg9:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L22)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's add a subsection for validate limitations (reformulate as you think is best, we need to make sure that the readers get these points)

There are some limitations set on the validate function. The purpose of these limitations is twofold:

* We want to avoid the sequencer having to do a lot of work only to discover that the validation failed and he's not eligible to charge a fee (if this is possible, he'd be completely exposed to DOS attacks). Validation, while now abstract and in control of the account owner rather than the protocol, should still be a simple operation. This is why in the future, we will place max steps limitation upon the `__validate__` function.
* Even if the validation is simple, we could still face the following attack: an attacker fills the mempool with transactions that are valid at time T. A sequencer may start executing them, thinking that at the time he will produce his block, they will still be valid. However, shortly after, at time T', the attacker sends one transaction that somehow invalidates all the previous ones and makes sure it's included before the sequencer gets to publish his block (the attacker may do this by offering higher fees for this one transaction). As a concrete example, think of many validate functions checking that the value of some storage slot is 1, and the attacker's transaction later sets it to 0. To handle this issue, we add some further limitations. Currently, StarkNet enforces that `__validate__` does not call external contracts.

Note (note box)
The property that we achieve with the above restrictions is that a single storage update may only invalidate transactions from a single account (and this is the best we can do, an account can always invalidate its own past transactions by changing its keys). Thus, the price (in fees) required to invalidate transactions in the mempool is linear in the number of unique accounts that we want to invalidate.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 09:15 UTC, ArielElp requested changes
> Reviewed 1 of 4 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 3 of 5 files reviewed, 11 unresolved discussions (waiting on @bbrandtom, @JameStark, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnscTfBRMeeXLItVyZ:-NJnscTfBRMeeXLItVy_:bnxw6ep) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L11)):*
> ```AsciiDoc
> 
> [id="examples"]
> == Examples of customizing account functionality
> ```

I think this section is better fitted as the last section on the introduction page (right after "What is account abstraction", see my comments on restructuring the introduction page)



_Code quote:_
```AsciiDoc
Examples of customizing account functionality
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 36 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbxSFE8l6inCyyMFcp:-NJnnoLD1t_s2aEiTxX2:b9tai26) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L36)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still don't like the use of "fair" here. Once you agree on a price per gas unit, this will determine the eventual fee. I suggest the following:

"and that fees can charged for the resources you use."

i.e. removing fair and changing "are" to "can"
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 37 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbyU7E7o4BjXbp0xbP:-NJnoqQx65jGHEUxgjJ1:bgu6gqz) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L37)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This paragraph should be in the first section (validate and execute functions), I see it under "replay protection" at the moment.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 1 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrefk1VYAKwGK_krS:-NJnrefk1VYAKwGK_krT:b9d1zdr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L1)):*
> ```AsciiDoc
> [id="validate_and_execute_functions"]
> ```

Let's rename "approach" to StarkNet Account Structure, and move the "StarkNet Account Structure" subsection to the beginning of the first section (what is now "validate and execute functions", and in the next comment I suggest to rename to "StarkNet Account Interface").
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 2 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrKFzDY289YU-9401:-NJnrKG-4hmNDIfe9KfY:b-yqh2oa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L2)):*
> ```AsciiDoc
> [id="validate_and_execute_functions"]
> == `&lowbar;&lowbar;validate&lowbar;&lowbar;` and `&lowbar;&lowbar;execute&lowbar;&lowbar;` functions
> ```

Let's rename this section to "StarkNet Account Interface."



_Code quote:_
```AsciiDoc
&lowbar;&lowbar;validate&lowbar;&lowbar;` and `&lowbar;&lowbar;execute&lowbar;&lowbar;` functions
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 22 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQWtq9Kcpou2hxO9e:-NJnlh8k6rc7CRb842sA:b-vy2nsj) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L22)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see that the section starting with "An account is a user's representation..." is now first, but let's add the title "What is an account" to it.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 25 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQpC21NyxBmdZiT_g:-NJnmLo97boR_w3pBISe:bg3l1tq) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L25)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The paragraph

"The idea behind account abstraction is to allow more flexibility in the management of accounts rather than have their behavior determined at the protocol level. This can be achieved by introducing account contracts - smart contracts with programmable logic that determines the user’s account.

Using account abstraction you can now program how your account functions."

is still under the first section, I think this should go to the beginning of the third section, which should be called "What is account abstraction" rather than "What is a StarkNet account"
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 22 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkc-lc4CkV3iH1jacE:-NJnvanQ8mZZ8y0OYouk:b-vxo80f) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L22)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You added it under "approach", I think it's better suited to this page
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 38 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImPh2t7kpMJdxWC_dY:-NJnwMyU6u13Hh1_NjKQ:b51winm) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L38)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We need to emphasize that this is only the situation today, I would start the sentence with:

Currently, the sequencer charges ...
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 2 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnxhdE1LLT6qRWY00l:-NJnxhdE1LLT6qRWY00m:b-3ikirg) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L2)):*
> ```AsciiDoc
> [id="validate_and_execute"]
> = `&lowbar;&lowbar;validate&lowbar;&lowbar;` and `&lowbar;&lowbar;execute&lowbar;&lowbar;`
> ```

I think that in titles it's better to use just "validate and execute", without the underscores.



_Code quote:_
```AsciiDoc
&lowbar;&lowbar;validate&lowbar;&lowbar;` and `&lowbar;&lowbar; [...]

2022-12-21 10:19 UTC, JameStark reviewed
> Reviewed 1 of 5 files at r1, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnscTfBRMeeXLItVyZ:-NJo8QLp0MgrV3zpvggv:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L11)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think this section is better fitted as the last section on the introduction page (right after "What is account abstraction", see my comments on restructuring the introduction page)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 36 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbxSFE8l6inCyyMFcp:-NJo8tua9FxBuSQTzisn:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L36)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I still don't like the use of "fair" here. Once you agree on a price per gas unit, this will determine the eventual fee. I suggest the following:

"and that fees can charged for the resources you use."

i.e. removing fair and changing "are" to "can"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 37 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbyU7E7o4BjXbp0xbP:-NJo97FF4_SAKEwfxnl-:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L37)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This paragraph should be in the first section (validate and execute functions), I see it under "replay protection" at the moment.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 1 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrefk1VYAKwGK_krS:-NJoAf1Q017s3fe-Ay7K:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L1)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's rename "approach" to StarkNet Account Structure, and move the "StarkNet Account Structure" subsection to the beginning of the first section (what is now "validate and execute functions", and in the next comment I suggest to rename to "StarkNet Account Interface").
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 2 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrKFzDY289YU-9401:-NJo8L7G0aTAkCvHhHqg:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L2)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's rename this section to "StarkNet Account Interface."
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 22 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQWtq9Kcpou2hxO9e:-NJo9nBX6PebCzY6Dq2g:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L22)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I see that the section starting with "An account is a user's representation..." is now first, but let's add the title "What is an account" to it.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 25 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIbQpC21NyxBmdZiT_g:-NJoA7i66qwImNNVePEp:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L25)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The paragraph

"The idea behind account abstraction is to allow more flexibility in the management of accounts rather than have their behavior determined at the protocol level. This can be achieved by introducing account contracts - smart contracts with programmable logic that determines the user’s account.

Using account abstraction you can now program how your account functions."

is still under the first section, I think this should go to the beginning of the third section, which should be called "What is account abstraction" rather than "What is a StarkNet account"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 22 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NIkc-lc4CkV3iH1jacE:-NJoBNa248j0Iu8MpQ6-:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L22)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

You added it under "approach", I think it's better suited to this page
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 38 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NImPh2t7kpMJdxWC_dY:-NJo7uy2-E977r1eBBGl:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L38)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

We need to emphasize that this is only the situation today, I would start the sentence with:

Currently, the sequencer charges ...
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 2 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnxhdE1LLT6qRWY00l:-NJoB2CQ8esHIv_k7qDH:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc#L2)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that in titles it's better to use just "validate and execute", without the underscores.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/validate_and_execute.adoc` line 31 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnw0xABPmL1FqzYCPU:-NJo7kTJ6QvZ55AcyrR9:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d5 [...]

2022-12-21 10:19 UTC, JameStark reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-21 10:31 UTC, JameStark reviewed
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-21 11:29 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 8 unresolved discussions (waiting on @bbrandtom, @JameStark, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnscTfBRMeeXLItVyZ:-NJoHbOWA5M2TVhvebcC:bstk0ta) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L11)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see that it moved
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 1 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrefk1VYAKwGK_krS:-NJoH-2TDM6H2W-PWEOY:b-rcecjb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L1)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we have a different name on the left sidebar, i.e. keep the title the same but only change the name on the left? If so then in the left bar I prefer "StarkNet Account Structure". WDYT?
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 2 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoHLu0EetL4e8nkdOZ:-NJoHLu0EetL4e8nkdO_:buhz841) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L2)):*
> ```AsciiDoc
> [id="starknet_account_structure"]
> == StarkNet account interface
> ```

Don't we do capitals in titles? (i.e StarkNet Account Interface)
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNPh37uRZdB7011X1:-NJoNPh37uRZdB7011X2:beswyc5) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
> ```AsciiDoc
> The key stages of transaction lifetime are:
> 
> .   A new transaction is sent to the mempool with a nonce
> ```

I think that this should be removed, the nonce isn't the emphasis here (you could also say "with a signature" or every other field in the tx)



_Code quote:_
```AsciiDoc
with a nonce
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 7 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNbU_6ZnjdGMo73Xh:-NJoNbUa-i0Dtj9_k1At:bevths8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L7)):*
> ```AsciiDoc
> 
> .   A new transaction is sent to the mempool with a nonce
> .   The sequencer selects a valid transaction from the mempool
> ```

The sequencer selects a transaction from the mempool and executes __validate__



_Code quote:_
```AsciiDoc
The sequencer selects a valid transaction from the mempool
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 8 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNjok6N_H6k11rzkr:-NJoNjok6N_H6k11rzks:b2nif2c) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L8)):*
> ```AsciiDoc
> .   A new transaction is sent to the mempool with a nonce
> .   The sequencer selects a valid transaction from the mempool
> .   If the transaction is valid, the _execute_ function is called
> ```

was



_Code quote:_
```AsciiDoc
is
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 9 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNnVc8L_jsGLUi1pn:-NJoNnVc8L_jsGLUi1po:bdm2sic) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L9)):*
> ```AsciiDoc
> .   The sequencer selects a valid transaction from the mempool
> .   If the transaction is valid, the _execute_ function is called
> .   If _execute_ is successful, the sequencer passes the transaction to the StarkNet prover
> ```

includes the transaction in the block, charges the fee, and proceeds to work on the next one (once the block is concluded, it will be sent to the prover)



_Code quote:_
```AsciiDoc
passes the transaction to the StarkNet prover
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 12 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoOFc39JmPpaq81GqU:-NJoOFc413hDZMlJTMLx:b-2dgtl4) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L12)):*
> ```AsciiDoc
> 
> [id="a_payment_mechanism"]
> == A payment mechanism
> ```

I think that we can remove this section, or replace it with another step in the above flow

There are some inaccuracies here, specifically, the sequencer doesn't run the StarkNet OS. The StarkNet OS only exists for proving (we express the claim "block is valid" via "the StarkNet OS ran successfully when given this block", the latter is something we can prove).


<!-- Sent from Reviewable.io -->

2022-12-21 13:42 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 2 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoHLu0EetL4e8nkdOZ:-NJouq6K3_enu72_pJhE:b-gxopw8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L2)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Don't we do capitals in titles? (i.e StarkNet Account Interface)
</blockquote></details>

Only on the first word. This is the standard we have across all docs currently


<!-- Sent from Reviewable.io -->

2022-12-21 13:53 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnscTfBRMeeXLItVyZ:-NJovH6J1dZuHIRPSJsT:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L11)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I don't see that it moved
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
not mandatory at the protocol level, a richer standard interface for accounts was developed by the community. This standard was developed by OpenZeppelin, in a
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 1 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrefk1VYAKwGK_krS:-NJoxPDy29DPY_iUR60a:bdy5wa5) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L1)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Can we have a different name on the left sidebar, i.e. keep the title the same but only change the name on the left? If so then in the left bar I prefer "StarkNet Account Structure". WDYT?
</blockquote></details>

Sure, yes I think Structure is better
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNPh37uRZdB7011X1:-NJovNBo5ldmP8Wty4RD:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that this should be removed, the nonce isn't the emphasis here (you could also say "with a signature" or every other field in the tx)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 7 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNbU_6ZnjdGMo73Xh:-NJovWFy9x2l28yo5wGq:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L7)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The sequencer selects a transaction from the mempool and executes __validate__
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 8 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNjok6N_H6k11rzkr:-NJovZuwB9Fh5LlfRxAu:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L8)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

was
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 9 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoNnVc8L_jsGLUi1pn:-NJovpmO8kIOB_j6rcbJ:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L9)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

includes the transaction in the block, charges the fee, and proceeds to work on the next one (once the block is concluded, it will be sent to the prover)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 12 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJoOFc39JmPpaq81GqU:-NJovzLFAN8HWpW4XbUC:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c2e29cca98b82f5ae481fbcf6d8179a1bc69706/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L12)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that we can remove this section, or replace it with another step in the above flow

There are some inaccuracies here, specifically, the sequencer doesn't run the StarkNet OS. The StarkNet OS only exists for proving (we express the claim "block is valid" via "the StarkNet OS ran successfully when given this block", the latter is something we can prove).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 13:53 UTC, JameStark reviewed
> Reviewed 3 of 4 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-21 14:05 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 1 at r8](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnrefk1VYAKwGK_krS:-NJp-6_61dQUfzYa6vBU:b-7rl0kd) ([raw file](https://github.com/starknet-io/starknet-docs/blob/7657c5ce54f75fd4d521acd2beb8592656a7490c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L1)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Sure, yes I think Structure is better
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-22 06:21 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 7 unresolved discussions (waiting on @bbrandtom, @JameStark, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnscTfBRMeeXLItVyZ:-NJsQ8GUCbZ4sQWUnKIc:b980dmu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L11)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, this paragraph was in-place (last paragraph of the interface section). I meant moving "Examples of customizing account functionality" to the last section of the introduction
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 2 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsUM309x35jpNVuXlG:-NJsUM309x35jpNVuXlH:b-x3jbgc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L2)):*
> ```AsciiDoc
> [id="what_is_an_account"]
> = What is an account?
> ```

Should this be a regular title (one that appears on the right bar)? 



_Code quote:_
```AsciiDoc
What is an account?
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsR1zp6EoWgr-3bUIQ:-NJsR1zp6EoWgr-3bUIR:behnhpj) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
> ```AsciiDoc
> The key stages of transaction lifetime are:
> 
> .   The sequencer selects a valid transaction from the mempool and executes `&lowbar;&lowbar;validate&lowbar;&lowbar;`
> ```

delete valid (there's no need to execute validate if you already know it was valid)



_Code quote:_
```AsciiDoc
valid
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 7 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsRaKJ5M1pis3ob5eQ:-NJsRaKJ5M1pis3ob5eR:b-phxfb7) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L7)):*
> ```AsciiDoc
> 
> .   The sequencer selects a valid transaction from the mempool and executes `&lowbar;&lowbar;validate&lowbar;&lowbar;`
> .   If the transaction is valid, the _execute_ function is called
> ```

It came out different than validate, I think you need one more underscore



_Code quote:_
```AsciiDoc
_execute_
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 8 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsT6pv-DaW3bN58CP3:-NJsT6pv-DaW3bN58CP4:b-jqz7xv) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L8)):*
> ```AsciiDoc
> .   The sequencer selects a valid transaction from the mempool and executes `&lowbar;&lowbar;validate&lowbar;&lowbar;`
> .   If the transaction is valid, the _execute_ function is called
> .   If _execute_ was successful, the sequencer includes the transaction in the block, charges the fee and proceeds to work on the next transaction (once the block is concluded, it will be sent to the prover)
> ```

ran successfully



_Code quote:_
```AsciiDoc
was successful
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 11 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsTm2i3TfvX-8d86j8:-NJsTm2i3TfvX-8d86j9:b2nhp9o) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L11)):*
> ```AsciiDoc
> 
> [id="a_payment_mechanism"]
> == A payment mechanism
> ```

The



_Code quote:_
```AsciiDoc
A
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 13 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsToOC-oZNMs0FEETg:-NJsToOC-oZNMs0FEETh:b-btozue) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L13)):*
> ```AsciiDoc
> == A payment mechanism
> 
> The sequencer receives fees in ETH in return for including transactions in a block.
> ```

I suggest adding the sentence: "For more details on how the transaction fee is computed, see [the fees section]"


<!-- Sent from Reviewable.io -->

2022-12-23 09:00 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc` line 11 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJnscTfBRMeeXLItVyZ:-NJyCMiPESXqusxwT42y:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9f00cd16e32846b79690ad98e16c19bf295f555c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/approach.adoc#L11)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

No, this paragraph was in-place (last paragraph of the interface section). I meant moving "Examples of customizing account functionality" to the last section of the introduction
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 2 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsUM309x35jpNVuXlG:-NJy9L_p7NgAtq66Cg6o:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L2)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Should this be a regular title (one that appears on the right bar)? 
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsR1zp6EoWgr-3bUIQ:-NJy9TPk8jY0omlX3Ig_:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

delete valid (there's no need to execute validate if you already know it was valid)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 7 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsRaKJ5M1pis3ob5eQ:-NJy9dOL3HlunJJMhLND:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L7)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

It came out different than validate, I think you need one more underscore
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 8 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsT6pv-DaW3bN58CP3:-NJy9jGx5NOs_srAOLGU:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L8)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

ran successfully
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 11 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsTm2i3TfvX-8d86j8:-NJy9nTOAjJ_d2LnIIAK:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L11)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 13 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsToOC-oZNMs0FEETg:-NJy9y_58SW329UB0hFC:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L13)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I suggest adding the sentence: "For more details on how the transaction fee is computed, see [the fees section]"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-23 09:00 UTC, JameStark reviewed
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-23 09:09 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 7 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-23 09:21 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 3 unresolved discussions (waiting on @bbrandtom, @JameStark, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 2 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsUM309x35jpNVuXlG:-NJyEjugA3BKgSL3eBaH:b6e78ds) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L2)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the right bar, on the left I think "Introduction to account abstraction" was a good title
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsR1zp6EoWgr-3bUIQ:-NJyF3VSEZPGT3DYhZou:bxkb4u3) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still there as far as I can see, what I was going for was:

"The sequencer selects a transaction from the mempool and executes __validate__" 
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 7 at r14](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJyHT6I0rgYNzLLBZ1P:-NJyHT6I0rgYNzLLBZ1Q:b2nif2c) ([raw file](https://github.com/starknet-io/starknet-docs/blob/2adc02c6c91e142f4cdae7a67e5b40fe43b861b6/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L7)):*
> ```AsciiDoc
> 
> .   The sequencer selects a valid transaction from the mempool and executes
> .   If the transaction is valid, the `&lowbar;&lowbar;execute&lowbar;&lowbar;` function is called
> ```

was



_Code quote:_
```AsciiDoc
is
```


<!-- Sent from Reviewable.io -->

2022-12-23 09:26 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc` line 2 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsUM309x35jpNVuXlG:-NJyI-7_1zN_eO9M85mB:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/introduction.adoc#L2)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I meant the right bar, on the left I think "Introduction to account abstraction" was a good title
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r12](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJsR1zp6EoWgr-3bUIQ:-NJyIJXMACWF-1ptgAju:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/6c544e261e74f1ac09ee63c37dd203654b8ca221/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Still there as far as I can see, what I was going for was:

"The sequencer selects a transaction from the mempool and executes __validate__" 
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 7 at r14](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJyHT6I0rgYNzLLBZ1P:-NJyIOqZ8GpjVEsKY8IJ:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/2adc02c6c91e142f4cdae7a67e5b40fe43b861b6/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L7)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

was
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-23 09:26 UTC, JameStark reviewed
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-23 09:45 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @bbrandtom, @JameStark, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc` line 6 at r15](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-NJyJZ-s9a9HmBg9pezp:-NJyJZ-s9a9HmBg9pezq:b-tjtbwh) ([raw file](https://github.com/starknet-io/starknet-docs/blob/1c8013ce02b9b40ca8a519880d7f1ca0a9e38a39/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/simplified_transaction_flow.adoc#L6)):*
> ```AsciiDoc
> The key stages of transaction lifetime are:
> 
> .   TThe sequencer selects a transaction from the mempool and executes `&lowbar;&lowbar;validate&lowbar;&lowbar;`
> ```

Extra T



_Code quote:_
```AsciiDoc
T
```


<!-- Sent from Reviewable.io -->

2022-12-23 10:02 UTC, ArielElp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133#-:-NJyQkHg4SYxX_GPnMxw:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @bbrandtom, @JameStark, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-23 10:03 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-23 10:05 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @stoobie)



<!-- Sent from Reviewable.io -->

2022-12-23 10:05 UTC, merged