docs(declaration,deployment): Enhance contract declaration and deployment documentation
starknet-io/starknet-docs pull request #1359
Opened 2024-09-20 01:00 UTC by omarespejel

## Description of the Changes

### Changes to Declaration Documentation

1. **Enhanced Introduction**
   - Added a clear explanation of what declaration means in Starknet
   - Introduced an analogy comparing declaration to registering a blueprint

2. **Visual Representation**
   - Added a Mermaid diagram showing the relationship between declaration and deployment

3. **Context for Separation**
   - Explained why declaration and deployment are separate steps in Starknet
   - Highlighted benefits like gas optimization and reusability

4. **C++ Analogy**
   - Included an analogy relating Starknet contract declaration to C++ concepts:
     - Writing contract code ≈ Defining a class in C++
     - Declaring contract ≈ Compiling class into object code
     - Deploying contract instance ≈ Creating an object of the class

5. **Verification Methods**
     - Using `starkli class-by-hash` command

### Changes to Deployment Documentation

1. **Expanded Introduction**
   - Enhanced explanation of the deployment process
   - Added a factory production analogy for clearer understanding

2. **Visual Representation**
   - Included a Mermaid diagram illustrating the deployment process

3. **Verification Methods**
     - Using `starkli class-hash-at` command

5. **Troubleshooting Guide**
   - New section on common deployment issues, focusing on the "address unavailable" error
   - Explained the cause of the error (address collision due to salt reuse)
   - Provided solution (using unique salt values)

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-1359/

### Check List

- [X] Changes have been done against main branch, and PR does not conflict
- [X] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/1359)

2024-09-23 11:30 UTC, ArielElp requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1359)* status: all files reviewed, 6 unresolved discussions (waiting on @omarespejel)

___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 24 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7TZWqn5QX-YzrBn-vs:-O7TZWqn5QX-YzrBn-vt:b-yoza4j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L24)):*
> ```AsciiDoc
> * Deploying a contract, i.e. creating an instance of the code you previously declared.
> 
> image::declaration-process.png[]
> ```

Declare contract --> Declare contract class

I'd remove the "class hash" cube since it's confusing IMO. It's an implementation detail that you refer to classes via class_hash.

Alternatively, you can, under "Declare contract class", add a row in a smaller font of "class_hash: 0x12345", and in each deploy write "deploy instance i of the class 0x12345". Though the second option sounds a bit too much to me.
___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 35 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7T_EO-8FtaCM0Ot-m7:-O7T_EO-8FtaCM0Ot-m8:b-3ihdff) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L35)):*
> ```AsciiDoc
> Declaration is the process of submitting your contract's code to the Starknet network, making it available for future deployments. It's a one-time process for each unique contract code. Think of declaration as registering a blueprint for your contract with the network.
> 
> We can draw a parallel with C++ programming:
> ```

I'd remove the c++ and java sections and say:

Contract classes are analogous to classes in Object Oriented Programming. The class is defined once, and there can be many instances of it.

anything more than that is too cumbersome in a "quick-start" page
___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 49 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7T_W0jDw8cZI6HLKQS:-O7T_W0jDw8cZI6HLKQT:b80f9i7) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L49)):*
> ```AsciiDoc
> Just as you can create multiple objects from a single class in C++, you can deploy multiple instances of a declared contract in Starknet.
> 
> === Why Separate Declaration and Deployment?
> ```

Same here, quick-start shouldn't be about deep diving into the network. Maybe consider editing this page https://starknet-io.github.io/starknet-docs/pr-1359/architecture-and-concepts/smart-contracts/contract-classes/, and only linking to it here
___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 184 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7Tah4X9Utl98KjEJj_:-O7Tah4X9Utl98KjEJja:b-lkavwl) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L184)):*
> ```AsciiDoc
> This hash is the identifier of the contract class in Starknet. You can think of it as the address of the contract class. You can use a block explorer like https://testnet.starkscan.co/class/0x00e68b4b07aeecc72f768b1c086d9b0aadce131a40a1067ffb92d0b480cf325d[StarkScan] to see the contract class hash in the blockchain.
> 
> Using Starkli: You can use the following command to retrieve the contract class by its hash:
> ```

I think getting the raw class in a quickstart guide is too low-level.
___
*[`components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc` line 28 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7Td1lq7854qUOR_fxZ:-O7Td1lq7854qUOR_fx_:bvzgu0z) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc#L28)):*
> ```AsciiDoc
> Deployment is the process of creating a live, functional instance of your declared smart contract on the Starknet network. It's like bringing a blueprint to life by constructing an actual building.
> 
> Let's use a factory production analogy:
> ```

I don't think the factory analogy should be in the quickstart guide. Potentially link to the contract classes page, but I suggest to remove this part.
___
*[`components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc` line 58 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7TdEcDEXiTZgd0KhDB:-O7TdEcDEXiTZgd0KhDC:b4eq8h1) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc#L58)):*
> ```AsciiDoc
> ----
> 
> Think of <CLASS_HASH> as the product code in our factory analogy, and <CONSTRUCTOR_INPUTS> as the specific settings for this product instance.
> ```

Same as above, in favor of removing


<!-- Sent from Reviewable.io -->

2024-09-24 00:51 UTC, omarespejel reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/1359)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @ArielElp)

___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 24 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7TZWqn5QX-YzrBn-vs:-O7WSMVj7WZoBgPB226h:b-vcwpf) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L24)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Declare contract --> Declare contract class

I'd remove the "class hash" cube since it's confusing IMO. It's an implementation detail that you refer to classes via class_hash.

Alternatively, you can, under "Declare contract class", add a row in a smaller font of "class_hash: 0x12345", and in each deploy write "deploy instance i of the class 0x12345". Though the second option sounds a bit too much to me.
</blockquote></details>

Done. I agree to keep it simple
___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 35 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7T_EO-8FtaCM0Ot-m7:-O7V7Ov87cizM1J_p-OU:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L35)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I'd remove the c++ and java sections and say:

Contract classes are analogous to classes in Object Oriented Programming. The class is defined once, and there can be many instances of it.

anything more than that is too cumbersome in a "quick-start" page
</blockquote></details>

Done.
___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 49 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7T_W0jDw8cZI6HLKQS:-O7WPSh65RXQ757gYDme:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L49)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Same here, quick-start shouldn't be about deep diving into the network. Maybe consider editing this page https://starknet-io.github.io/starknet-docs/pr-1359/architecture-and-concepts/smart-contracts/contract-classes/, and only linking to it here
</blockquote></details>

Done.
___
*[`components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc` line 184 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7Tah4X9Utl98KjEJj_:-O7WTDJL-XsViFkjuWcX:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/declare-a-smart-contract.adoc#L184)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think getting the raw class in a quickstart guide is too low-level.
</blockquote></details>

Done.
___
*[`components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc` line 28 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7Td1lq7854qUOR_fxZ:-O7WU7Lb94V7LCWIpj8J:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc#L28)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I don't think the factory analogy should be in the quickstart guide. Potentially link to the contract classes page, but I suggest to remove this part.
</blockquote></details>

Done.
___
*[`components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc` line 58 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/1359#-O7TdEcDEXiTZgd0KhDB:-O7WVdT78DsAmJs7lf5Z:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/fd3aad22030dbd051b665439dc83fb5d25f7663a/components/Starknet/modules/quick-start/pages/deploy-a-smart-contract.adoc#L58)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Same as above, in favor of removing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-24 00:53 UTC, omarespejel commented
Thanks for the review @ArielElp!

2024-10-28 18:01 UTC, LandauRaz commented
Hey @omarespejel, let's talk about this PR privately (closing it in the meantime).

2024-11-19 20:30 UTC, LandauRaz commented
Partially addressed in #1416.

2025-01-23 21:49 UTC, closed without merging