Update overview.adoc
starknet-io/starknet-docs pull request #1381
Opened 2024-11-04 12:24 UTC by Shani-roz

updated the links to the tokens lists on mainnet and sepolia

### Description of the Changes

I updated the links to the tokens lists on mainnet and sepolia to the json files that contain all the tokens.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against main branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2024-11-04 13:35 UTC, LandauRaz commented
Hey @Shani-roz, thank you very much for the contribution 🙏
To expedite the review of this PR, can you please:
1. Add the specific URL(s) of the content that this PR addresses under "PR Preview URL"
2. Edit the PR title according to the convention specified under "Check List"
Thanks!

2024-11-04 16:40 UTC, LandauRaz requested changes

2024-11-04 16:40 UTC, LandauRaz commented on components/Starknet/modules/starkgate/pages/overview.adoc
> +| Mainnet | link:https://beta.starkgate.starknet.io/static/tokens.json[mainnet.json]
These files are no longer called "mainnet.json" and "sepolia.json" anymore, so please remove their names (i.e., the square bracket parts)
Please also change "Sepolia testnet" to "Sepolia".

2024-11-04 16:40 UTC, LandauRaz commented on components/Starknet/modules/starkgate/pages/overview.adoc
> +L1 and L2 addresses for StarkGate bridges and supported tokens are listed in the JSON files shown in the table xref:#table_StarkGate_token_addresses[].
Please also remove the "in the Starknet GitHub repository" part in the second paragraph of "Supported tokens in StarkGate" (currently line 33) as well.

2024-11-04 16:46 UTC, LandauRaz commented
@Shani-roz, I left a couple of small comments and will merge the PR as soon as you address them.
Also, thanks for adding the URL under "PR Preview URL" and adding a title according to the convention specified under "Check List", but please note how I edited both for future PRs.

2024-11-06 15:35 UTC, LandauRaz requested changes

2024-11-06 15:43 UTC, Shani-roz commented on components/Starknet/modules/starkgate/pages/overview.adoc
> +| StarkGate bridged tokens JSON files
I know that's not what you meant but I thought that just removing the links' names and show the URLs also wouldn't look so good. wdyt?

2024-11-06 15:50 UTC, LandauRaz commented on components/Starknet/modules/starkgate/pages/overview.adoc
> +| StarkGate bridged tokens JSON files
1. I think removing the links' names and showing the URLs is still better. You can shorten them a bit, e.g. `https://beta.starkgate.starknet.io/static/tokens.json` -> `beta.starkgate.starknet.io/tokens.json`
2. You also can just call both of them `tokens.json`
Up to you!

2024-11-07 18:30 UTC, LandauRaz approved these changes

2024-11-07 18:30 UTC, merged