Update scarb installation to use asdf
starknet-io/starknet-docs pull request #1398
Opened 2024-11-11 06:55 UTC by amanusk

### Description of the Changes

Updating the env setup instructions to use asdf and not scarb script

If the PR is related to an open issue, please also link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Please paste the specific URL(s) of the content that this PR addresses here.

### Check List

- [X] Changes have been done against main branch, and PR does not conflict
- [X] PR title is meaningful, e.g: `fix: minor typos in README`

2024-11-12 13:57 UTC, LandauRaz requested changes

2024-11-12 13:57 UTC, LandauRaz commented on components/Starknet/modules/quick-start/pages/environment-setup.adoc
> +Installing Scarb with `asdf` seamlessly integrates with the Cairo VSCode extension, and allows to easily switch between different versions of Scarb, globally or per project.
Please be consistent and use either asfd or `asfs` throughout the entire subsection

2024-11-12 13:57 UTC, LandauRaz commented on components/Starknet/modules/quick-start/pages/environment-setup.adoc
> +Installing Scarb with `asdf` seamlessly integrates with the Cairo VSCode extension, and allows to easily switch between different versions of Scarb, globally or per project.
Please add a link to the "Visual Studio Code Extension" page in the "Tools and resources" section

2024-11-13 12:57 UTC, LandauRaz commented on components/Starknet/modules/quick-start/pages/environment-setup.adoc
> +. Follow the installation steps of `asdf`` on the link:https://asdf-vm.com/guide/getting-started.html[official website].
`asdf`` should be `asdf`

2024-11-13 12:58 UTC, LandauRaz commented on components/Starknet/modules/quick-start/pages/environment-setup.adoc
> +See additional commands for updating Scarb and switching between versions in the link:https://asdf-vm.com/manage/commands.html[asdf documentation], or by running `asdf --help`.
[asdf documentation] should be [`asdf` documentation]

2024-11-13 12:59 UTC, LandauRaz commented on components/Starknet/modules/quick-start/pages/environment-setup.adoc
> +|Starknet Foundry
Please open a separate PR for changes regarding Starknet Foundry

2024-11-13 19:51 UTC, LandauRaz approved these changes

2024-11-13 19:51 UTC, merged

2025-01-07 19:28 UTC, chadoh commented
This change undid https://github.com/starknet-io/starknet-docs/pull/876 by @stoobie, which switched this repo to use an installation guide from [docs-common-content](https://github.com/starknet-io/docs-common-content). Was that intentional? If I want to make future changes to the installation guide, should I make them in this repository, or in `docs-common-content`?

2025-01-08 12:54 UTC, LandauRaz commented
Hey @chadoh, `docs-common-content` is now deprecated so all changes should be done in this repository.