Add Keccak System Call Documentation
starknet-io/starknet-docs pull request #1461
Opened 2024-12-26 09:09 UTC by Nityam573

# Add Keccak System Call Documentation

## Description
Add missing documentation for the Keccak system call to the System Calls section, following the established AsciiDoc format.

## Changes
- Add complete documentation for `keccak_syscall`
- Include function signature and description
- Document arguments and return values
- Add practical usage example
- Include notes on common use cases
- Match existing AsciiDoc format and style

## Additional Notes
- Documentation follows the established format of other system calls
- Example demonstrates typical usage scenario
- Added notes section to highlight common use cases and Ethereum compatibility
- Links to correct file in Cairo corelib (needs to be done)

## Related Issues
Closes #1457

2024-12-29 09:39 UTC, LandauRaz commented
Thanks for the contribution, @Nityam573!
Before I can merge your PR, please make sure to follow the checklist I just recopied to the first response :) (I kept what you'd already written, but please delete it afterwards).

2024-12-29 10:46 UTC, Nityam573 commented
@LandauRaz Done with the specified changes 
Please review

2024-12-30 06:51 UTC, LandauRaz commented
Thanks 🙏 Note though that the link should be to the specific content you edited (I did it for you this time:)

2024-12-30 07:03 UTC, LandauRaz requested changes

2024-12-30 07:03 UTC, LandauRaz commented on components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/system-calls-cairo1.adoc
> +=== Example
The way to use this syscall is not directly, but with functions in `[keccak.cairo](https://github.com/starkware-libs/cairo/blob/67c6eff9c276d11bd1cc903d7a3981d8d0eb2fa2/corelib/src/keccak.cairo)` that themselves use the syscall under the hood.
Please change the example accordingly and add an explanation under "Description".

2024-12-30 07:03 UTC, LandauRaz commented on components/Starknet/modules/architecture-and-concepts/pages/smart-contracts/system-calls-cairo1.adoc
> +[NOTE]
This note just reiterates stuff that has already been mentioned (unless I'm missing something), so please delete it.

2024-12-30 18:08 UTC, Nityam573 reviewed
All changes are resolved

2025-01-02 05:52 UTC, Nityam573 commented
@LandauRaz Please review the changes

2025-01-02 06:48 UTC, LandauRaz approved these changes

2025-01-02 06:48 UTC, LandauRaz commented
Great! Thanks again 🙏

2025-01-02 06:49 UTC, merged