Add deploy_account missing from docs
starknet-io/starknet-docs pull request #198
Opened 2023-01-05 15:07 UTC by JameStark

### Description of the Changes

Deploy account new since v0.10.3

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2023-01-08 11:14 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 192 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLFvIka4EiUGysWszYK:-NLFvIka4EiUGysWszYL:bzhd9s2) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f73a4403276b9d2e1b37aaf44924e33217b2e7aa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L192)):*
> ```AsciiDoc
> The following is an example of the new `deploy_account` transaction:
> 
> ```json
> ```

Remove the example, have a table instead like for the other transactions
The fields in the table should be what you see in the below example
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 223 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLFvrY0DcK1rhtXVZ4T:-NLFvrY13AnuO_hTeN0x:b-k8yewx) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f73a4403276b9d2e1b37aaf44924e33217b2e7aa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L223)):*
> ```AsciiDoc
> ====
> 
> ### Validate deploy
> ```

Remove from here, add this under a new page under account abstraction: "Deploying new Accounts". Start with an introduction to the problem of deploying new accounts, then describe the deploy_account transaction solution, and then discuss validate_deploy and potential DOS vectors that it prevents.



_Code quote:_
```AsciiDoc
### Validate deploy
```


<!-- Sent from Reviewable.io -->

2023-01-11 10:37 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 192 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLFvIka4EiUGysWszYK:-NLVOwnJ2YEgM8fbsLnd:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f73a4403276b9d2e1b37aaf44924e33217b2e7aa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L192)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Remove the example, have a table instead like for the other transactions
The fields in the table should be what you see in the below example
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
alidate deploy
```


<!-- Sent from Reviewable.io -->

2023-01-11 10:48 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 223 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLFvrY0DcK1rhtXVZ4T:-NLVRNWC2yOVDQKtaxl9:b-c3hhjl) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f73a4403276b9d2e1b37aaf44924e33217b2e7aa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L223)):*
> Start with an introduction to the problem of deploying new accounts, then describe the deploy_account transaction solution, and then discuss validate_deploy and potential DOS vectors that it prevents.

Does this include the 'API changes' section too?


<!-- Sent from Reviewable.io -->

2023-01-12 13:57 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-01-16 12:55 UTC, bbrandtom requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 223 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLFvrY0DcK1rhtXVZ4T:-NLudUtx8v5fhm3GsyoH:bbghmyr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f73a4403276b9d2e1b37aaf44924e33217b2e7aa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L223)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think maybe you forgot to push? I still see it here
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 184 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLucf2A-R-A5UxFoCtW:-NLucf2A-R-A5UxFoCtX:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L184)):*
> ```AsciiDoc
> * stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash
> 
> ## Deploy account
> ```





_Suggestion:_
```AsciiDoc
Deploy account transaction
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 188 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLudA_75PWJbtoO80Vp:-NLudA_75PWJbtoO80Vq:b-nwrkb8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L188)):*
> ```AsciiDoc
> Since xref:ROOT:version_notes.adoc#version0.10.1[StarkNet v0.10.1] the `deploy_account` transaction replaces the `deploy` transaction for deploying account contracts.
> 
> To use it, you should first add enough funds to your account address to pay the transaction fee, you can invoke `deploy_account`.
> ```

something is missing here, the sentence is not correct



_Code quote:_
```AsciiDoc
 you can i
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 190 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLudJzp15zF5a4y_ZR3:-NLudJzp15zF5a4y_ZR4:b-ytab1q) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L190)):*
> ```AsciiDoc
> To use it, you should first add enough funds to your account address to pay the transaction fee, you can invoke `deploy_account`.
> 
> The following is an example of the new `deploy_account` transaction:
> ```

This is not an example, it is the structure



_Code quote:_
```AsciiDoc
The following is an example o
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 215 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLudO_WBWNaI7H7j1-W:-NLudO_WBWNaI7H7j1-X:b23ge2y) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L215)):*
> ```AsciiDoc
> * verify that the address has funds to pay for the deployment
> * execute the constructor with the given arguments
> * execute the `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;` entry point
> ```

What is validate_deploy? it is not explained anywhere in the docs



_Code quote:_
```AsciiDoc
`&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;`
```


<!-- Sent from Reviewable.io -->

2023-01-16 13:51 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 223 at r1](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLFvrY0DcK1rhtXVZ4T:-NLuqFVA1rO0YnoDzPLL:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/f73a4403276b9d2e1b37aaf44924e33217b2e7aa/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L223)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I think maybe you forgot to push? I still see it here
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
A new validation entrypoint has been added to avoid being able to drain funds from a pre-funded address.
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 184 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLucf2A-R-A5UxFoCtW:-NLupApcC7WIxPrYMtTy:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L184)):*
> ```AsciiDoc
> * stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash
> 
> ## Deploy account
> ```

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 188 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLudA_75PWJbtoO80Vp:-NLupjk69UKje9Bvko3l:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L188)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

something is missing here, the sentence is not correct
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 190 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLudJzp15zF5a4y_ZR3:-NLupkGr0wuwBGiFnDK5:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L190)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

This is not an example, it is the structure
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 215 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLudO_WBWNaI7H7j1-W:-NLuq7ie2SsiIhSOamL6:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/585cc8e3d4e452e6d9cfc1c260a1df8708048be3/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L215)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

What is validate_deploy? it is not explained anywhere in the docs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-16 13:53 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-01-17 11:52 UTC, bbrandtom requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 9 unresolved discussions (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 2 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzZQd2-wTf_GiNuhgt:-NLzZQd2-wTf_GiNuhgu:b8aiau8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L2)):*
> ```AsciiDoc
> [id="deploying_new_accounts"]
> = Deploying new accounts
> ```

we are missing the flow here
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 4 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzXe8qAULOUF3efSZ4:-NLzXe8qAULOUF3efSZ5:bv8e35t) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L4)):*
> ```AsciiDoc
> = Deploying new accounts
> 
> Prior to xref:documentation:starknet_versions:version_notes.adoc#version0.10.1[StarkNet version 0.10.1] it was possible for a `deploy_account` transaction to be manipulated in two undesirable ways:
> ```

We didn't have deploy account transactions before v0.10.1.
You describe the deliberations we had when we tried to design this flow.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 14 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzY2H320CpVbfe1S1z:-NLzY2H320CpVbfe1S2-:b-fdt5qg) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L14)):*
> ```AsciiDoc
> 
> * Limited # of Cairo steps
> * Limited # of builtin applications
> ```

are those limitations for both the validate_deploy and the constructor? It is not clear



_Code quote:_
```AsciiDoc
* Limited # of Cairo steps
* Limited # of builtin applications
* No external contract calls (library calls and self-calls are allowed)
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 17 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzYG1eBTUSd5WQAQEb:-NLzYG1eBTUSd5WQAQEc:b-8np699) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L17)):*
> ```AsciiDoc
> * No external contract calls (library calls and self-calls are allowed)
> 
> ## Validate deploy
> ```

This is not required in all contracts/accounts. We should state that this entrypoint should be included only in contracts that want to allow this flow.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 39 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzYmk4EGCmn2KlK2g8:-NLzYmk4EGCmn2KlK2g9:b-6g6n95) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L39)):*
> ```AsciiDoc
> Consider an account with the following constructor signature:
> 
> ```json
> ```

Don't we have Cairo syntax highlighting?
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 80 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzZK9c1RthqBpk27GM:-NLzZK9c1RthqBpk27GN:bpoo7tx) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L80)):*
> ```AsciiDoc
> * No external contract calls (library calls and self-calls are allowed)
> 
> The precise limits are still being researched internally and will be shared in the future. In particular, we may block additional system calls that introduce the risk of validation being time-dependent, e.g. `get_block_timestamp` or `get_block_number`.
> ```

seems like this repeats what was stated above and does not clarify why introducing validate_deploy solves this attack.



_Code quote:_
```AsciiDoc
** Draining the User’s funds:
We need to make sure that if a user pre-funded their account, then there is no way to drain those funds. Additionally, they must approve the amount they're willing to pay for the deployment. This is solved by the introduction of `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;`.

The limitations on validation/constructor execution involve:

* Limited # of Cairo steps
* Limited # of builtin applications
* No external contract calls (library calls and self-calls are allowed)

The precise limits are still being researched internally and will be shared in the future. In particular, we may block additional system calls that introduce the risk of validation being time-dependent, e.g. `get_block_timestamp` or `get_block_number`.
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 209 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzZXITBDYE0haBHUTF:-NLzZXITBDYE0haBHUTG:b-xd8lfc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/54822ea242bce42a74df8b1e4c232c2b30912f43/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L209)):*
> ```AsciiDoc
> 
> 
> ### Transaction flow
> ```

we don't have this in other transactions. I any case, it is missing from the explanation page.


<!-- Sent from Reviewable.io -->

2023-01-17 15:17 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 9 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 39 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzYmk4EGCmn2KlK2g8:-NM-ITJ8BGJNPjB_QFK8:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L39)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Don't we have Cairo syntax highlighting?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-17 18:41 UTC, bbrandtom reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @ArielElp and @JameStark)



<!-- Sent from Reviewable.io -->

2023-01-18 14:49 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 2 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzZQd2-wTf_GiNuhgt:-NM404BcEpB_51iSwYY9:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L2)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

we are missing the flow here
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 4 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzXe8qAULOUF3efSZ4:-NM405_z9HrkwjzaoEGf:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L4)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

We didn't have deploy account transactions before v0.10.1.
You describe the deliberations we had when we tried to design this flow.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 14 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzY2H320CpVbfe1S1z:-NM45k8g3OEXFodGegtm:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L14)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

are those limitations for both the validate_deploy and the constructor? It is not clear
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 17 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzYG1eBTUSd5WQAQEb:-NM49Lmg20Dr6s8WncM4:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L17)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

This is not required in all contracts/accounts. We should state that this entrypoint should be included only in contracts that want to allow this flow.
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
 validation entrypoint has been added to avoid being able to drain funds from a pre-funded address.
```


<!-- Sent from Reviewable.io -->

2023-01-18 15:00 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 209 at r3](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzZXITBDYE0haBHUTF:-NM4M_4M9cvhh9rYo9Qb:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/54822ea242bce42a74df8b1e4c232c2b30912f43/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L209)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

we don't have this in other transactions. I any case, it is missing from the explanation page.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-18 15:00 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 80 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzZK9c1RthqBpk27GM:-NM4OJ6L9LetJmAXltIB:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L80)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

seems like this repeats what was stated above and does not clarify why introducing validate_deploy solves this attack.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-19 12:55 UTC, JameStark reviewed
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-01-19 12:55 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-01-19 13:58 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-01-22 11:22 UTC, bbrandtom requested changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 14 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzY2H320CpVbfe1S1z:-NMOCDSBCWsL90mqLqVi:bo2m8jg) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L14)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The limitations are also on the constructor
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 12 at r14](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NMOC3pfD7abMamjT-5G:-NMOC3pg0C6t3AI07-V0:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/85680f194f123e000d67d8f4b09f3e2b8c4bd796/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L12)):*
> ```AsciiDoc
> In order to deploy a new account on StarkNet you need to complete the following steps:
> 
> * Decide on the account type you want to deploy
> ```





_Suggestion:_
```AsciiDoc
contract
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 83 at r14](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NMOCTEwElCpzEU5VGK6:-NMOCTEwElCpzEU5VGK7:b-5767la) ([raw file](https://github.com/starknet-io/starknet-docs/blob/85680f194f123e000d67d8f4b09f3e2b8c4bd796/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L83)):*
> ```AsciiDoc
> ====
> 
> ## API changes
> ```

Why is this here? I think it is unrelated


<!-- Sent from Reviewable.io -->

2023-01-23 09:10 UTC, JameStark reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 14 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NLzY2H320CpVbfe1S1z:-NMSsood4zuq3j02-qJe:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b011a4d883e96893fc42941bcdc0e75f25ffec4d/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L14)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

The limitations are also on the constructor
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 12 at r14](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NMOC3pfD7abMamjT-5G:-NMSkq-fCBxU_VQjvRxe:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/85680f194f123e000d67d8f4b09f3e2b8c4bd796/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L12)):*
> ```AsciiDoc
> In order to deploy a new account on StarkNet you need to complete the following steps:
> 
> * Decide on the account type you want to deploy
> ```

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 83 at r14](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NMOCTEwElCpzEU5VGK6:-NMSswiz2HEoWshlLrYk:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/85680f194f123e000d67d8f4b09f3e2b8c4bd796/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L83)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Why is this here? I think it is unrelated
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-23 09:16 UTC, JameStark reviewed
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-01-23 09:38 UTC, JameStark reviewed
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-02-14 13:29 UTC, bbrandtom submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-:-NOF6K40-z4LbKrEXW53:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)



<!-- Sent from Reviewable.io -->

2023-02-15 18:43 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @bbrandtom and @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 4 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLKkMP9kgO0L4c8JzE:-NOLKkMP9kgO0L4c8JzF:b-vumhcn) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L4)):*
> ```AsciiDoc
> = Deploying new accounts
> 
> Since xref:documentation:starknet_versions:version_notes.adoc#version0.10.1[StarkNet version 0.10.1] the historical method of deploying accounts on StarkNet, the `deploy` transaction has been removed.
> ```

add comma:

, the `deploy` transaction,
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 6 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLKzL197uBufx1sNrd:-NOLKzL197uBufx1sNre:bscjy3i) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L6)):*
> ```AsciiDoc
> Since xref:documentation:starknet_versions:version_notes.adoc#version0.10.1[StarkNet version 0.10.1] the historical method of deploying accounts on StarkNet, the `deploy` transaction has been removed.
> 
> It has now been replaced with the `deploy_account` transaction which allows you to deploy an account and additionally be charged fairly for the deployment.
> ```

I suggest replacing this with "and pay fees from a pre-funded address (thus solving the issue of how to pay fees while not yet having a deployed account)"

I don't like the use of fairly + It doesn't seem like something the user is happy/cares about



_Code quote:_
```AsciiDoc
and additionally be charged fairly for the deployment
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 39 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLLqgtDEN6l2MUOTxi:-NOLLqgtDEN6l2MUOTxj:b-qa48pe) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L39)):*
> ```AsciiDoc
> To prevent the above scenarios, a new optional validation entrypoint is provided: `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;`.
> 
> This enforces some limitations on `deploy_account` transactions and the constructor via validation execution, namely:
> ```

I don't understand the later part of the sentence, suggest replacing with:

"This suggests some limitations on the constructor and `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;` executions, namely:"



_Code quote:_
```AsciiDoc
This enforces some limitations on `deploy_account` transactions and the constructor via validation execution
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 45 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLMFE_1yVORBl6Vj41:-NOLMFE_1yVORBl6Vj42:b-970rgc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L45)):*
> ```AsciiDoc
> * No external contract calls (library calls and self-calls are allowed)
> 
> This entrypoint should be included in any accounts or contracts that wish to allow this updated flow.
> ```

new deployment flow



_Code quote:_
```AsciiDoc
updated flow
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 186 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLMrPxDsyJjOnlHUvd:-NOLMrPxDsyJjOnlHUve:b-khyymu) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L186)):*
> ```AsciiDoc
> ## Deploy account transaction
> 
> Since xref:ROOT:version_notes.adoc#version0.10.1[StarkNet v0.10.1] the `deploy_account` transaction replaces the `deploy` transaction for deploying account contracts.
> ```

link is broken



_Code quote:_
```AsciiDoc
xref:ROOT:version_notes.adoc#version0.10.1[StarkNet v0.10.1]
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 188 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLMw-362nNBLoCv1z0:-NOLMw-362nNBLoCv1z1:b-ua970m) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L188)):*
> ```AsciiDoc
> Since xref:ROOT:version_notes.adoc#version0.10.1[StarkNet v0.10.1] the `deploy_account` transaction replaces the `deploy` transaction for deploying account contracts.
> 
> To use it, you should first add enough funds to your account address to pay the transaction fee. You can then invoke the `deploy_account` transaction.
> ```

you should first pre-fund your would-be account address so that you could pay the transaction fee (see here for more details).

here = link to the new deploy new accounts page



_Code quote:_
```AsciiDoc
you should first add enough funds to your account address to pay the transaction fee
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 209 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLNZKjBuKpXeu6_0Tm:-NOLNZKjBuKpXeu6_0Tn:byn4o9b) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L209)):*
> ```AsciiDoc
> 
> 
> ### Transaction flow
> ```

I suggest removing this section from here, you already have it in the above page and we can link to it here (see my previous comment)



_Code quote:_
```AsciiDoc
### Transaction flow
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 219 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLNfxAEfAFS5xf1O7O:-NOLNfxAEfAFS5xf1O7P:b8za38e) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L219)):*
> ```AsciiDoc
> * advance the nonce to 1
> 
> [NOTE]
> ```

please add this note in the other page (didn't see it there)



_Code quote:_
```AsciiDoc
[NOTE]
====
In determining the contract address, deployer address 0 will be used.
====
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 224 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLNCLF6cbkdfZiadzv:-NOLNCLF6cbkdfZiadzw:bufjpr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L224)):*
> ```AsciiDoc
> ====
> 
> ## API changes
> ```

remove this section, we don't need it here (only in the version updates page)


<!-- Sent from Reviewable.io -->

2023-02-20 08:28 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 1 of 5 files reviewed, 12 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 4 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLKkMP9kgO0L4c8JzE:-NOhvJG15kS_y13UL09e:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

add comma:

, the `deploy` transaction,
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 6 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLKzL197uBufx1sNrd:-NOhtNTk1mWXB6DAKi6u:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L6)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I suggest replacing this with "and pay fees from a pre-funded address (thus solving the issue of how to pay fees while not yet having a deployed account)"

I don't like the use of fairly + It doesn't seem like something the user is happy/cares about
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 39 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLLqgtDEN6l2MUOTxi:-NOhtlFt77U6fOpJQMgh:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L39)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I don't understand the later part of the sentence, suggest replacing with:

"This suggests some limitations on the constructor and `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;` executions, namely:"
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 45 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLMFE_1yVORBl6Vj41:-NOhtxVIBewNt1q3PhCx:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L45)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

new deployment flow
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 186 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLMrPxDsyJjOnlHUvd:-NOhu46_E0A39iSbBlMD:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L186)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

link is broken
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 188 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLMw-362nNBLoCv1z0:-NOhuTSR042c8ckEyBz0:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L188)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

you should first pre-fund your would-be account address so that you could pay the transaction fee (see here for more details).

here = link to the new deploy new accounts page
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 209 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLNZKjBuKpXeu6_0Tm:-NOhugiU4ZDxKaljv3aF:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L209)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I suggest removing this section from here, you already have it in the above page and we can link to it here (see my previous comment)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 219 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLNfxAEfAFS5xf1O7O:-NOhvxs6-7zu2DA5FRgX:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L219)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

please add this note in the other page (didn't see it there)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 224 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLNCLF6cbkdfZiadzv:-NOhv6xmCrZBJfzfxokT:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L224)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove this section, we don't need it here (only in the version updates page)
</blockquote></details>

Done.



_Code quote:_
```AsciiDoc
 the following minor API changes apply sin
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 226 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOhv42DDd-_mkFAYgVm:-NOhv42DDd-_mkFAYgVn:b-a276ct) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L226)):*
> add this note in the other page


<!-- Sent from Reviewable.io -->

2023-02-20 08:28 UTC, JameStark reviewed
> Reviewed 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: all files reviewed, 12 unresolved discussions (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2023-02-20 09:02 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @JameStark)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 4 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLKkMP9kgO0L4c8JzE:-NOi1pbtCnXWyl_f5V4X:b-ut7np8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L4)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 39 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLLqgtDEN6l2MUOTxi:-NOi0wtkDDp-k0ig1ty-:b8qvri) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L39)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reading it again I think that there is a better way to say this. Let's connect it with the previous paragraph and rephrase a bit:

To prevent the scenario described in the first point, a new optional validation entrypoint is provided: `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;`. To prevent the potential DOS attack from the second point, we introduce This implements some limitations on the constructor and &lowbar;&lowbar;validate_deploy&lowbar;
&lowbar; executions, namely:
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 226 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOhv42DDd-_mkFAYgVm:-NOi2k1PCKoU8sC4K9SM:bsk8rzc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L226)):*
<details><summary><i>Previously, JameStark wrote…</i></summary><blockquote>

> add this note in the other page
</blockquote></details>

I don't think API changes should appear in the account abstraction pages
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 192 at r18](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOi2SMD1EGyCCI9I3q2:-NOi2SMD1EGyCCI9I3q3:bb7og0d) ([raw file](https://github.com/starknet-io/starknet-docs/blob/75cd1b33dc25d4343560cfd3893903d0ad581017/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L192)):*
> ```AsciiDoc
> To use it, you should first pre-fund your would-be account address so that you could pay the
> transaction fee (see xref:documentation:architecture_and_concepts:Account_Abstraction
> /deploying_new_accounts.adoc[here] for more details).. You can then invoke the `deploy_account`
> ```

send



_Code quote:_
```AsciiDoc
invoke
```


<!-- Sent from Reviewable.io -->

2023-02-20 11:34 UTC, JameStark reviewed
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @JameStark)



<!-- Sent from Reviewable.io -->

2023-02-20 11:44 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 4 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLKkMP9kgO0L4c8JzE:-NOid1L3EORbWx9dGLrE:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L4)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I don't see it
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc` line 39 at r17](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOLLqgtDEN6l2MUOTxi:-NOiceht52-uxgCN7eNF:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/cd4b8f2b5916b241b18a04e857f3401189dea90c/components/StarkNet/modules/architecture_and_concepts/pages/Account_Abstraction/deploying_new_accounts.adoc#L39)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Reading it again I think that there is a better way to say this. Let's connect it with the previous paragraph and rephrase a bit:

To prevent the scenario described in the first point, a new optional validation entrypoint is provided: `&lowbar;&lowbar;validate_deploy&lowbar;&lowbar;`. To prevent the potential DOS attack from the second point, we introduce This implements some limitations on the constructor and &lowbar;&lowbar;validate_deploy&lowbar;
&lowbar; executions, namely:

</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc` line 192 at r18](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-NOi2SMD1EGyCCI9I3q2:-NOicm0V1q9Ongw8KM6t:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/75cd1b33dc25d4343560cfd3893903d0ad581017/components/StarkNet/modules/architecture_and_concepts/pages/Blocks/transactions.adoc#L192)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

send
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-20 11:51 UTC, ArielElp reviewed
> Reviewed 1 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @JameStark)



<!-- Sent from Reviewable.io -->

2023-02-20 11:57 UTC, ArielElp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/198#-:-NOifyTP5tmYJFfD8uUP:bnfp4nl)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @JameStark)



<!-- Sent from Reviewable.io -->

2023-02-20 12:04 UTC, merged