docs: Add contract syntax page
starknet-io/starknet-docs pull request #543
Opened 2023-06-12 17:24 UTC by ArielElp

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

https://starknet-io.github.io/starknet-docs/pr-543/documentation/architecture_and_concepts/Cairo_on_Starknet/contract-syntax/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/starknet-docs/543)

2023-06-13 11:43 UTC, bbrandtom requested changes
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/543)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 1 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoX70lEyxVdvv_SwXf:-NXoX70lEyxVdvv_SwXg:buhtixj) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L1)):*
> ```AsciiDoc
> # Cairo 1 Contract Syntax
> ```

Let's change this to "migration guide", this is not a docs fo the Contract Syntax.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 43 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXPcsAgWFml6WocVy:-NXoXPcsAgWFml6WocVz:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L43)):*
> ```AsciiDoc
> 
> * Add a generic parameter to the trait, here we use the name `TContractState` as it stands for the state of your contract
> * For view functions, add the `self: TContractState` argument
> ```





_Suggestion:_
```AsciiDoc
external
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 44 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXS7GDk74f6NKzvFY:-NXoXS7GDk74f6NKzvFZ:undefined) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L44)):*
> ```AsciiDoc
> * Add a generic parameter to the trait, here we use the name `TContractState` as it stands for the state of your contract
> * For view functions, add the `self: TContractState` argument
> * For external functions, add the `self: @TContractState` argument
> ```





_Suggestion:_
```AsciiDoc
view
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 71 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXfii1e10leLNwekq:-NXoXfij-k1tzKDzOy2V:b-s7qotf) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L71)):*
> ```AsciiDoc
> trait ICounterContract<TContractState> {
>    fn increase_counter(ref self: TContractState, amount: u128);
>    fn decrease_counter(ref self: TContractState);
> ```

missing `amount`, also true below
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 75 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXqiF-7YoKjiHgMp2:-NXoXqiF-7YoKjiHgMp3:b72nhx4) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L75)):*
> ```AsciiDoc
> }
> 
> #[starknet::contract]
> ```

you are not mentioning this attribute anywhere
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 110 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXtp129x617Yu0xH5:-NXoXtp129x617Yu0xH6:b5d8fbr) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L110)):*
> ```AsciiDoc
> trait ICounterContract<TContractState> {
>    fn increase_counter(ref self: TContractState, amount: u128);
>    fn decrease_counter(ref self: TContractState);
> ```

missing amount
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 117 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoY3XICDW3gio7w3jJ:-NXoY3XICDW3gio7w3jK:b-c6cssn) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L117)):*
> ```AsciiDoc
> mod CounterContract {
>    #[external(v0)]
>    impl CounterContract of super::ICounterContract<ContractState> {
> ```

this is not explained - is it constant?
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 118 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXw5V9-XQr5Dv37qN:-NXoXw5V9-XQr5Dv37qO:bdkwarv) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L118)):*
> ```AsciiDoc
>    #[external(v0)]
>    impl CounterContract of super::ICounterContract<ContractState> {
>       fn increase_counter(amount: u128) { ... }
> ```

missing `TContractState`?


<!-- Sent from Reviewable.io -->

2023-06-14 15:54 UTC, ArielElp reviewed
> Reviewed 1 of 5 files at r7, 2 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/543)* status: 4 of 12 files reviewed, 8 unresolved discussions (waiting on @bbrandtom)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 1 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoX70lEyxVdvv_SwXf:-NXuZq_J9xJCfyubnqd2:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L1)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Let's change this to "migration guide", this is not a docs fo the Contract Syntax.
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 43 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXPcsAgWFml6WocVy:-NXuZFCyAh1D4yTu1X6Z:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L43)):*
> ```AsciiDoc
> 
> * Add a generic parameter to the trait, here we use the name `TContractState` as it stands for the state of your contract
> * For view functions, add the `self: TContractState` argument
> ```

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 44 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXS7GDk74f6NKzvFY:-NXuZFSaATJpLxqnO1nB:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L44)):*
> ```AsciiDoc
> * Add a generic parameter to the trait, here we use the name `TContractState` as it stands for the state of your contract
> * For view functions, add the `self: TContractState` argument
> * For external functions, add the `self: @TContractState` argument
> ```

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 71 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXfii1e10leLNwekq:-NXoluLu2OucgXGY7u60:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L71)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

missing `amount`, also true below
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 75 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXqiF-7YoKjiHgMp2:-NXubId73MD4iu07nfRG:b-86bfhc) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L75)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

you are not mentioning this attribute anywhere
</blockquote></details>

added section
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 110 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXtp129x617Yu0xH5:-NXolv2TCHoE1b8Sq2Xp:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L110)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

missing amount
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 117 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoY3XICDW3gio7w3jJ:-NXonMvDCJJgVCBuZXNx:b-g6lfay) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L117)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

this is not explained - is it constant?
</blockquote></details>

you choose the name of the impl, other than that, it's constant (you need to implement the interface trait and give it the concrete ContractState type)
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 118 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXoXw5V9-XQr5Dv37qN:-NXon60X4O5WkBosbJff:b-g1fnou) ([raw file](https://github.com/starknet-io/starknet-docs/blob/9aebdb288e6cbe88ac0f02f639be3e78e3fd4659/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L118)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

missing `TContractState`?
</blockquote></details>

added (you need a concrete type, not the generic)


<!-- Sent from Reviewable.io -->

2023-06-15 09:03 UTC, bbrandtom requested changes
> Reviewed 1 of 5 files at r7, 1 of 8 files at r8, 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/543)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc` line 18 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyHeth0jR73PhTQ4Ft:-NXyHetiDM0o30Mga4Dm:bvpttp9) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc#L18)):*
> ```AsciiDoc
> 
> * xref:computation[Computational complexity]: the heavier the transaction, the larger its portion in the proof verification cost.
> <<<<<<< HEAD
> ```

what is this??
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc` line 23 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyHgBv1xWacc3YkGiW:-NXyHgBw9LD-zoKkdwK6:bnp9pq3) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc#L23)):*
> ```AsciiDoc
> =======
> * xref:_on_chain_data[On chain data]: L1 calldata cost originating from xref:_on_chain_data[data availability] and L2→L1 messages.
> >>>>>>> add subtitles
> ```

what subtitles?


<!-- Sent from Reviewable.io -->

2023-06-15 09:03 UTC, bbrandtom approved these changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/543)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)



<!-- Sent from Reviewable.io -->

2023-06-15 09:05 UTC, stoobie requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/543)* status: all files reviewed, 19 unresolved discussions (waiting on @ArielElp)

___
*[`components/StarkNet/modules/architecture_and_concepts/nav.adoc` line 36 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXy7uzyBOXhqLOiBFbO:-NXy7uzz0lOv9o_nV7mo:bu7l21r) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/nav.adoc#L36)):*
> ```AsciiDoc
> ** Cairo on Starknet
> *** xref:Cairo_on_Starknet/cairo-1-and-sierra.adoc[Cairo 1.0 and Sierra]
> *** xref:Cairo_on_Starknet/contract-syntax.adoc[Contract Syntax - Migration Guide]
> ```

Use sentence case.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 1 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXy7ebqEHvtXoSLD-Ms:-NXy7ebqEHvtXoSLD-Mt:b-7bxwwe) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L1)):*
> ```AsciiDoc
> # Contract Syntax - Migration Guide
> ```

Use Asciidoc syntax.

Use sentence case, as per style guide. Actually there are lots of places where you need to fix this, not just in this PR.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 4 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXy86i58OlZ9RZQENRm:-NXy86i58OlZ9RZQENRn:b-kbgxum) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L4)):*
> ```AsciiDoc
> 
> With the link:https://github.com/starkware-libs/cairo/releases/tag/v2.0.0-rc0[v2.0.0 release] of
> the Cairo compiler, the Starknet contract syntax has evolved. This affects how external
> ```

_This_ should always have a noun after it. _This evolution_.

Alternatively:

`With the link:https://github.com/starkware-libs/cairo/releases/tag/v2.0.0-rc0[v2.0.0 release] of
the Cairo compiler, the Starknet contract syntax has evolved, affecting the organization of external...`
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 7 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXy9cQJ9u06Hm9mVleo:-NXy9cQJ9u06Hm9mVlep:b-difogz) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L7)):*
> ```AsciiDoc
> functions, storage, and events are organized inside the contract.
> 
> This page highlights the technical steps required to migrate from the old Starknet contract
> ```

Is this really necessary? Generally, sefl-referential text is considered fluff when writing minimalistically. Consider whether this actually adds anything. You already say it's a migration guide in the title.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 10 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXy8mx100yQuZXg6gre:-NXy8mx100yQuZXg6grf:bllm4l6) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L10)):*
> ```AsciiDoc
> syntax to the new.
> 
> For a comprehensive breakdown of the changes, see the link:https://community.starknet.io/t/cairo-1-contract-syntax-is-evolving/94794[community forum post].
> ```

I don't like the word "breakdown" here. Why not just keep it simple? 

`For more information on changes, see <link>Title of post</ink in the community forum.`
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 12 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXy9JlI9zEUb2xTFicO:-NXy9JlI9zEUb2xTFicP:bybwaem) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L12)):*
> ```AsciiDoc
> For a comprehensive breakdown of the changes, see the link:https://community.starknet.io/t/cairo-1-contract-syntax-is-evolving/94794[community forum post].
> 
> ## New contract syntax - concrete steps for migrating
> ```



You really should start using Asciidoc syntax. It's confusing having the mix and you want to guide contributors to do the right thing by example.
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 14 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyAdtR8bYk6G-FkD9J:-NXyAdtR8bYk6G-FkD9K:bwzvh57) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L14)):*
> ```AsciiDoc
> ## New contract syntax - concrete steps for migrating
> 
> Given a contract written with the previous compiler version (v1.1.0), you can follow the steps below in order to make it compatible with the new syntax.
> ```

I don't see any steps. Steps are numbered. 

Get rid of all the headings. All these sections are individual steps. This is one procedure.



_Code quote:_
```AsciiDoc
you can follow the steps
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 18 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyAM4t4LaC-t5thNeC:-NXyAM4t4LaC-t5thNeD:br2x5te) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L18)):*
> ```AsciiDoc
> ### Contract Anotation
> 
> Outside the contract module, Starknet related attributes are expected to have the `starknet::` prefix.
> ```

Passive. Make this an active step. Tell me to do something:



_Suggestion:_
```AsciiDoc
. Change the contract annotation from `#[contract]` to `#[starknet::contract]`. For example:
+
[tabs]
...
```
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 69 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyCNmz0X9S09T3iRLF:-NXyCNmz0X9S09T3iRLG:bs2dogg) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L69)):*
> ```AsciiDoc
> ====
> 
> ### Contract Interface
> ```

Delete
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 71 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyCRVVA6sqboDYZ5bE:-NXyCRVVA6sqboDYZ5bF:b-qqqfaa) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L71)):*
> ```AsciiDoc
> ### Contract Interface
> 
> Gather your contract’s external/view function signatures under a trait anotated with `#[starknet::interface]`:
> ```

I don't understand external/view. Don't use a slash like this, it's ambiguous. Does it mean either external or view? Or does it mean that _external_ and _view_ are synonyms? If they are synonyms, then just pick one term and stick with it.



_Suggestion:_
```AsciiDoc
. Gather your contract’s external/view function signatures under a trait annotated with `#[starknet::interface]`:
```
___
*[`components/St [...]

2023-06-15 12:15 UTC, JameStark reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/543)* status: 11 of 12 files reviewed, 19 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 14 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyAdtR8bYk6G-FkD9J:-NXypf7d9iUARPZj0M0c:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L14)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I don't see any steps. Steps are numbered. 

Get rid of all the headings. All these sections are individual steps. This is one procedure.
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 18 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyAM4t4LaC-t5thNeC:-NXypM1i7DzTqNVb9mmR:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L18)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Passive. Make this an active step. Tell me to do something:
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 71 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyCRVVA6sqboDYZ5bE:-NXyr8jU1kPhFs5KjFHP:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L71)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I don't understand external/view. Don't use a slash like this, it's ambiguous. Does it mean either external or view? Or does it mean that _external_ and _view_ are synonyms? If they are synonyms, then just pick one term and stick with it.
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 71 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyCr-x0wQsZmkJGNZ7:-NXyr9bH71z0hS68EQ7H:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L71)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

anotated => annotated
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 73 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyD-kMDMlvgs58dsBU:-NXyrQukBrYa3eUTdJ44:be9sl1b) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L73)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

* What is a generic parameter? Is the word "generic" necessary or useful?
* I don't understand if these list items are steps that should be done in order, or guidelines, not all of which I necessarily need to do every time. Introduce this unordered list with some context.
</blockquote></details>

Done (generic parameter is a data type)
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 73 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyD76X0o5QCGxNvqAL:-NXyrytRAHMGGRxDPjxA:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L73)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

This is two sentences.

Don't use "we".

Here we use => "For example", or "In this example..." or something similar.
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 75 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyDcayE_Ozsq2RqGe5:-NXys5k96P5IbapRhvYR:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L75)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

This is a full sentence. Add a period here and to all the items in this list. User periods for list items that are full sentences.
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 77 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyENYT-CrzQmkmYxaT:-NXyss7h2UZUhb3pw80u:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L77)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Is the example tied to "Static functions that do not touch storage or emit events do not require an addition argument" or to "Gather your contract’s external/view function signatures under a trait anotated with #[starknet::interface]:"? It's not clear.
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 113 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyEndJAyI9YvAYGHvI:-NXysvmA39mgamk0ZlDy:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L113)):*
> ```AsciiDoc
> ====
> 
> ### Add Interface Impl
> ```

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 115 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyEtGY3oad8b3l-Dra:-NXyt1RH-72xqq-iebWz:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L115)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

What is an _impl_? If it's a construct, should it be in monospace?
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 159 at r10](https://reviewable.io/reviews/starknet-io/starknet-docs/543#-NXyFMaFDXw8-dQckKBA:-NXyylHPAKQ1WFv69qay:bb6un1j) ([raw file](https://github.com/starknet-io/starknet-docs/blob/b0f72577fac6d2deeef2bcf574bcf2455fb1e1fa/components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc#L159)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

The heading discusses one attribute, but the sentence opens referring to multiple attributes. I don't understand. In any case, delete the heading.
</blockquote></details>

Done
___
*[`components/StarkNet/modules/architecture_and_concepts/pages/Cairo_on_Starknet/contract-syntax.adoc` line 161 at r10](https://reviewable.io/reviews/starknet-io/star [...]

2023-08-24 11:22 UTC, closed without merging