docs: Reword limit on resource allocation for fees
starknet-io/starknet-docs pull request #731
Opened 2023-08-11 12:25 UTC by JameStark

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2023-08-13 05:48 UTC, LandauRaz commented on components/Starknet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
> -Suppose, for example, that a transaction uses 10,000 Cairo steps and 500 Pedersen hashes. We can squeeze at most 40,000 such transactions into our hypothetical trace (20,000,000/500). Therefore, its
Why was this deleted?

2023-08-13 05:48 UTC, LandauRaz commented on components/Starknet/modules/architecture_and_concepts/pages/Fees/fee-mechanism.adoc
> +Notice we completely ignored the number of Cairo steps in this transaction performance estimation, as it is not the limiting factor.
If the example was deleted, then so should this sentence

2023-08-22 12:15 UTC, LandauRaz commented on components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/Fees/fee-mechanism.adoc
> +Notice we completely ignored the number of Cairo steps in this transaction performance estimation, as it is not the limiting factor.
This should be outside of [IMPORTANT] along with the deleted paragraph (why was it deleted in the first place?):

> Suppose, for example, that a transaction uses 10,000 Cairo steps and 500 Pedersen hashes. We can squeeze at most 40,000 such transactions into our hypothetical trace (20,000,000/500). Therefore, its gas price will be correlated with 1/40,000 of the cost of submitting proof.

I.e., this should be:

> The proof will be closed and sent to L1 when any of these components becomes full.
> Suppose, for example, that a transaction uses 10,000 Cairo steps and 500 Pedersen hashes. We can squeeze at most 40,000 such transactions into our hypothetical trace (20,000,000/500). Therefore, its gas price will be correlated with 1/40,000 of the cost of submitting proof.
> Notice we completely ignored the number of Cairo steps in this transaction performance estimation, as it is not the limiting factor.
> 
> [IMPORTANT]
> The allocation of resources among built-in operations must be predetermined; it's not possible to decide post-execution to include only 20,000,001 Pedersen hashes without additional components.
> This safeguards fairness and prevents manipulation, ensuring integrity in proof generation and fee determination.

WDYT?

2023-11-09 08:09 UTC, stoobie requested changes

2023-11-09 12:50 UTC, JameStark commented
Closing PR in favour of https://github.com/starknet-io/starknet-docs/pull/928

Branch very outdated so have cherrypicked only the changes needed

2023-11-09 12:50 UTC, closed without merging