[doc] Adding system calls
starknet-io/starknet-docs pull request #79
Opened 2022-10-19 11:11 UTC by stoobie

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2022-10-26 13:20 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-79/documentation/ .

2022-10-30 16:41 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79)* status: 0 of 2 files reviewed, 17 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 73 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdamEu3dQlI4JxR0pi:-NFdamEu3dQlI4JxR0pj:ber8yiv) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L73)):*
> ```AsciiDoc
> `_class_hash_`:: The class hash of the contract to be deployed
> `_contract_address_salt_`:: The salt, an arbitrary value provided by the sender, used in the computation of the xref:Contracts/contract-address.adoc[contract's address].
> `_constructor_calldata_size_`:: The size, in bytes, of the constructor's calldata.
> ```

replace with "The number of arguments to the constructor"
the size is not in bytes, it's the size of the array in the next parameter (so the number of felts)
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 106 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdbeNpCrUXSJWvIzel:-NFdbeNpCrUXSJWvIzem:b-17iueg) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L106)):*
> ```AsciiDoc
> .Arguments
> 
> `_keys_len_`:: ???
> ```

The number of the event's keys (analogous to Ethereum's event topics, these keys can be filtered over with the (starknet_getEvents)[https://github.com/starkware-libs/starknet-specs/blob/c270b8170684bb09741672a7a4ae5003670c3f43/api/starknet_api_openrpc.json#L569] RPC method)
The event keys
The number of the event's data elements (analogous to Ethereum's event data)
The event's data 
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 143 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFddy81-wQNpuv5GEUW:-NFddy81-wQNpuv5GEUX:bv3syeg) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L143)):*
> ```AsciiDoc
> .Return values
> 
> // Does "the number of the block" mean "the block's ID"???
> ```

No in the sense that it does not define the block (the block hash captures that)
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 197 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdeqZj2PcMAfJXFOIJ:-NFdeqZj2PcMAfJXFOIK:b-2aeliw) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L197)):*
> ```AsciiDoc
> .Description
> 
> Returns the address of the calling contract or 0 if the transaction was not initiated by another contract.
> ```

replace "transaction" with "call" (this was also present in the old one)
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 201 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdf-vq-vR7NlXelPv_:-NFdf-vq-vR7NlXelPva:b-7tkpbx) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L201)):*
> ```AsciiDoc
> .Arguments
> 
> // It appears that __caller_address__ is something you need to supply when calling this function, but the description says that __call_address__ is actually what is returned. Is the `->` in the syntax actually supposed to indicate that __caller_address__ is the return value?
> ```

You don't need to supply it, what appears after `->` is indeed the return value
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 300 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdfa2S78GcKRt_ib90:-NFdfa2S78GcKRt_ib91:b-g1l259) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L300)):*
> ```AsciiDoc
> +
> // What does "intended" mean?
> * the intended StarkNet OS version
> ```

Change to "the transaction's version" and remove the above comment
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 370 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdfwWf2VlLUp07tFbS:-NFdfwWf2VlLUp07tFbT:b-t6nky7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L370)):*
> ```AsciiDoc
> .Description
> 
> // Does this call the function/L1 handler, or tell the OS to call function/L1 handler???
> ```

everything here requests the OS to do something, the better formulation would be the former imo (calls rather than tell the OS to...)
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 376 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdgITUAjNIwieiRqyL:-NFdgITUAjNIwieiRqyM:b-5ece6c) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L376)):*
> ```AsciiDoc
> 
> // Who would consume the l1->L2 message?
> // How do you enter the symbol "→"
> ```

there's some code for it, you can copy/paste



_Code quote:_
```AsciiDoc
→
```
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 377 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdgO4b9zAoCTqGZTlY:-NFdgO4b9zAoCTqGZTlZ:b-119xmt) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L377)):*
> ```AsciiDoc
> // Who would consume the l1->L2 message?
> // How do you enter the symbol "→"
> // Once more, I'm against using a symbol that is outside the normal set of characters we use day to day. I think that "L1-L2" is almost, if not exactly, as clear as "L1→L2" and less bug-prone.
> ```

I think the arrow is clearer, and I don't see what bugs can result from it, it's just another ASCII symbol
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 379 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdiJfz6UMCGNjiq5CW:-NFdiJfz6UMCGNjiq5CX:bje6x2l) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L379)):*
> ```AsciiDoc
> // Once more, I'm against using a symbol that is outside the normal set of characters we use day to day. I think that "L1-L2" is almost, if not exactly, as clear as "L1→L2" and less bug-prone.
> When you invoke an L1 handler with this system call, no L1→L2 message
> // Consumed by who?
> ```

You can read more about the flow of L1->L2 messages in the docs. Usually, applying L1_handlers only happens by the sequencer as a consumption of a message. Via this system call, you're calling an L1 handler from another contract. 
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 382 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdhlTa1WL5C-5uxM4C:-NFdhlTa1WL5C-5uxM4D:bsqfz9u) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L382)):*
> ``` [...]

2022-11-08 06:09 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79)* status: 0 of 2 files reviewed, 18 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 73 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdamEu3dQlI4JxR0pi:-NFi77Cx4n8VQSpKNZt7:b-xyfm7n) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L73)):*
> ...it's the size of the array in the next parameter (so the number of felts)
If this is the same as the number of felts, that is, the size of the array in `_constructor_calldata_`, then why is this parameter necessary? Why doesn't the syscall just use the number of felts in `_constructor_calldata_`?
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 106 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdbeNpCrUXSJWvIzel:-NFiE5de5m3mnLwwUBeI:bb71pro) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L106)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The number of the event's keys (analogous to Ethereum's event topics, these keys can be filtered over with the (starknet_getEvents)[https://github.com/starkware-libs/starknet-specs/blob/c270b8170684bb09741672a7a4ae5003670c3f43/api/starknet_api_openrpc.json#L569] RPC method)
The event keys
The number of the event's data elements (analogous to Ethereum's event data)
The event's data 
</blockquote></details>

PTAL
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 143 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFddy81-wQNpuv5GEUW:-NFiE94u7kB-5Q8kfH8g:b-si1zii) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L143)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

No in the sense that it does not define the block (the block hash captures that)
</blockquote></details>

So then what is the block number?
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 197 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdeqZj2PcMAfJXFOIJ:-NFiGC9x2p3q9xbomjNX:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L197)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

replace "transaction" with "call" (this was also present in the old one)
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 201 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdf-vq-vR7NlXelPv_:-NFiGD2M6Kfb2CJPxnDs:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L201)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

You don't need to supply it, what appears after `->` is indeed the return value
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 300 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdfa2S78GcKRt_ib90:-NFiGYWK1dgH_IZ9zjtd:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L300)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Change to "the transaction's version" and remove the above comment
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 370 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdfwWf2VlLUp07tFbS:-NGDK-4i8Ugzy5Du88Pe:b6fk22g) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L370)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

everything here requests the OS to do something, the better formulation would be the former imo (calls rather than tell the OS to...)
</blockquote></details>

OK. I agree. Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 376 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdgITUAjNIwieiRqyL:-NFiJspSAfGQQyeuS7ux:b2nhb2c) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L376)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

there's some code for it, you can copy/paste
</blockquote></details>

Ack
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 377 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdgO4b9zAoCTqGZTlY:-NFiJfJIA5fMbGEI2VQx:b-5znnfw) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L377)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think the arrow is clearer, and I don't see what bugs can result from it, it's just another ASCII symbol
</blockquote></details>

Fine. I just read that in AsciiDoc I can just enter -> and this will be rendered as →.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 382 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdhlTa1WL5C-5uxM4C:-NFiMEMj1VP_Zw8ksOF8:b2nhb2c) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L382)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This system call
</blockquote></details>

Ack
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 383 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFiMbLs4d97T69-AXbu:-NFiMbLt3ofH6LgAXjjl:b-9mgp60) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L383)):*
> ```AsciiDoc
> 
> // "This enables" what does "this" refer to? The fact that no L1-L2 message is consumed?
> This enables an L1 handler to use the logic inside a different L1 handler from an existing class.
> ```

@arielelp I don't understand "a different L1 handler from an existing class"...does this mean that one existing class (let's call it "snoopy.cairo") Contains multiple L1 handlers, let's call two of them Charlie and Woodstock. So are you saying that the L1 handler Charlie can use the inside the L1 handler Woodstock?
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 399 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdiq4F0rNVLt556b2c:-NFiNyCy4IKmISjm4orJ:b-oz9pfs) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls [...]

2022-11-08 06:10 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79)* status: 0 of 2 files reviewed, 18 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 379 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdiJfz6UMCGNjiq5CW:-NGKr1Od5oDtFlyZ9VvO:bb6sh2i) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L379)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

You can read more about the flow of L1->L2 messages in the docs. Usually, applying L1_handlers only happens by the sequencer as a consumption of a message. Via this system call, you're calling an L1 handler from another contract. 
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2022-11-08 09:41 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79)* status: 0 of 2 files reviewed, 18 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 73 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdamEu3dQlI4JxR0pi:-NGLavADAsUtDrWr5rS1:b-9hsb4v) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L73)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

> ...it's the size of the array in the next parameter (so the number of felts)
If this is the same as the number of felts, that is, the size of the array in `_constructor_calldata_`, then why is this parameter necessary? Why doesn't the syscall just use the number of felts in `_constructor_calldata_`?
</blockquote></details>

Please check now.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 383 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFiMbLs4d97T69-AXbu:-NGLbL8L-ELDK2dvoeM3:b-hibtya) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L383)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

@arielelp I don't understand "a different L1 handler from an existing class"...does this mean that one existing class (let's call it "snoopy.cairo") Contains multiple L1 handlers, let's call two of them Charlie and Woodstock. So are you saying that the L1 handler Charlie can use the inside the L1 handler Woodstock?
</blockquote></details>

Changed. PTAL.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 399 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/79#-NFdiq4F0rNVLt556b2c:-NGLbOgoCTxvmDWg6nqD:b-7ya4b8) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L399)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

So is size always the number of field elements?
</blockquote></details>

I changed "size, in bytes" to "size, in felts".


<!-- Sent from Reviewable.io -->

2022-11-15 15:00 UTC, ArielElp requested changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79)* status: all files reviewed, 3 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 143 at r2](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NFddy81-wQNpuv5GEUW:-NGvmLiL1Mz2ygQG27aw:b6ns2bq) ([raw file](https://github.com/starknet-io/starknet-docs/blob/c6b5ab8f2bf64d0ff753036a5397b0f1513183c8/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L143)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

So then what is the block number?
</blockquote></details>

What's written (the number of the block in which the transaction is executed). You do know it in advance, but you don't know the block identifier (hash) as you don't know what transactions are going to be in it. Not sure if there's something still open here
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 105 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGviXQT55GnQuzQtJBc:-NGviXQT55GnQuzQtJBd:b-t31y06) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L105)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth=35]
> `_keys_len_`:: The number of keys in the event. Analogous to Ethereum's event topics, you can use the link:https://github.com/starkware-libs/starknet-specs/blob/c270b8170684bb09741672a7a4ae5003670c3f43/api/starknet_api_openrpc.json#L569RPC[starknet_getEvents] method to filter these keys.
> ```

filter by



_Code quote:_
```AsciiDoc
filter
```
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 364 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvjOOiBcLWaRIt1-iz:-NGvjOOiBcLWaRIt1-j-:b2un0lb) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L364)):*
> ```AsciiDoc
> .Description
> 
> Calls the requested function or an L1 handler in any previously declared class.
> ```

remove, this has to be an L1 handler



_Code quote:_
```AsciiDoc
function or an
```
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 368 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvkgBK0aedKP4pBxNd:-NGvkgBK0aedKP4pBxNe:bwz2lhh) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L368)):*
> ```AsciiDoc
> Same as the `library_call` system call, but also enables you to call an L1 handler that cannot otherwise be called directly. For more information, see StarkNet's xref:L1-L2_Communication/messaging-mechanism.adoc#l1-l2_messages[messaging mechanism].
> 
> When you invoke an L1 handler with this system call, the recipient address does not consume an L1->L2 message.
> ```

I prefer the original wording:

When an L1 handler is invoked via this syscall, no L1→L2 message is consumed.

-----------
The reason that I prefer it is that it's not the recipient address that is consuming the message (the sequencer is doing the "consumption", i.e. adds a transaction applying an l1 handler as a result of seeing something on L1).



_Code quote:_
```AsciiDoc
When you invoke an L1 handler with this system call, the recipient address does not consume an L1->L2 message.
```


<!-- Sent from Reviewable.io -->

2022-11-15 15:08 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 105 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGviXQT55GnQuzQtJBc:-NGvonr-8Pl0qVzzy2Sz:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L105)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

filter by
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 364 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvjOOiBcLWaRIt1-iz:-NGvohCeAhrzPU-7liKM:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L364)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove, this has to be an L1 handler
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 368 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvkgBK0aedKP4pBxNd:-NGvo8SDDXSd7l_QXmtS:bze8ckw) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L368)):*
Done. I changed it to:
>When you invoke an L1 handler with this system call, the sequencer does not consume an L1->L2 message.


<!-- Sent from Reviewable.io -->

2022-11-15 15:08 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 465 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvpPk98-4llaCcCUCL:-NGvpPk98-4llaCcCUCM:b-s4zeox) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L465)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth=35]
> `_address_`:: The address of the calling contract.
> ```

The address of the storage key we want to read
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 506 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvpK7T6MzPekdBSBWW:-NGvpK7T6MzPekdBSBWX:b-546w9n) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L506)):*
> ```AsciiDoc
> 
> [horizontal,labelwidth=35]
> `_address_`:: The address of the calling contract.
> ```

The address of the storage key we want to write to
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 507 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvp6V4ETTCKjdQuXgj:-NGvp6V4ETTCKjdQuXgk:b-ozg3x8) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L507)):*
> ```AsciiDoc
> [horizontal,labelwidth=35]
> `_address_`:: The address of the calling contract.
> `_value_`:: The value of the key.
> ```

The value to be written at the given key


<!-- Sent from Reviewable.io -->

2022-11-15 15:12 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 465 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvpPk98-4llaCcCUCL:-NGvpmyz6ZhulJyHBn1V:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L465)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The address of the storage key we want to read
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 506 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvpK7T6MzPekdBSBWW:-NGvqCSc-uhmUm5WnA7G:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L506)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The address of the storage key we want to write to
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 507 at r5](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvp6V4ETTCKjdQuXgj:-NGvqC5c-WmsfqmK136p:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ea0d11a800c0273f22795d4d6f05a7eac61749e9/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L507)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The value to be written at the given key
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-15 15:18 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc` line 480 at r6](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-NGvpu_eCZ41V6Bm85pA:-NGvqe4m1yWb3WxVOxZh:b-896fix) ([raw file](https://github.com/starknet-io/starknet-docs/blob/ba1b53f32107663534db4ceb56ba03cd75f85762/components/StarkNet/modules/develop/pages/Contracts/system-calls.adoc#L480)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

let value = storage_read(3534535754756246375475423547453)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-15 15:57 UTC, ArielElp submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r6, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-:-NGw-Xxx4Rh9LBwSiiqZ:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @bbrandtom)



<!-- Sent from Reviewable.io -->

2022-11-17 09:14 UTC, JameStark approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-io/starknet-docs/79#-:-NH3rcd-8IyoxH0pmjfj:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ArielElp and @bbrandtom)



<!-- Sent from Reviewable.io -->

2022-11-17 09:14 UTC, merged