Limit and triggers gas costs
starknet-io/starknet-docs pull request #901
Opened 2023-10-25 13:33 UTC by JameStark

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2023-10-25 14:09 UTC, stoobie commented on components/Starknet/modules/tools/pages/limits_and_triggers.adoc
> +|Max Cairo steps for `validate`| The maximum number of computational steps, measured in Cairo steps for a `validate` function.  |1M |1M
```suggestion
|Max Cairo steps for `validate`| The maximum number of computational steps, measured in Cairo steps, for a `validate` function.  |1M |1M
```

2023-10-26 09:54 UTC, stoobie requested changes

2023-11-08 12:11 UTC, JameStark commented on components/Starknet/modules/tools/pages/limits_and_triggers.adoc
> +|Max Cairo steps for `validate`| The maximum number of computational steps, measured in Cairo steps for a `validate` function.  |1M |1M
Done

2023-11-08 13:54 UTC, stoobie requested changes
Two suggestions awaiting response.

2023-11-08 13:54 UTC, stoobie commented on components/Starknet/modules/tools/pages/limits_and_triggers.adoc
> +|Block limit (gas)| Certain Starknet operations, such sending messages between L1 and L2, consume Ethereum gas. The current L1 state update
```suggestion
|Block limit (gas)| Certain Starknet operations, such as sending messages between L1 and L2, consume Ethereum gas. The current L1 state update
```

2023-11-13 08:02 UTC, merged