Fix: several typos in the documentation
starknet-io/starknet-docs pull request #929
Opened 2023-11-11 08:03 UTC by tudorpintea999

### Description of the Changes

Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.

2023-11-15 15:16 UTC, stoobie requested changes
Great comments! Thank you so much :)

Please correct the few things I mentioned, and then it's good to go.

If you prefer that I take care of it, just let me know.

2023-11-15 15:16 UTC, stoobie commented on components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-abi.adoc
> +You may not want to nest enums when serializing the event. For example, if you write an ERC20 as a component (not a contract) that is pluggable anywhere, you may not want the contract to modify the k
```suggestion
You may not want to nest enums when serializing the event. For example, if you write an ERC-20 as a component, not a contract, that is pluggable anywhere, you might not want the contract to modify the keys of known events such as `Transfer`.
```

2023-11-15 15:16 UTC, stoobie commented on components/Starknet/modules/cli/pages/starkli.adoc
> +`--gateway_url`:: Sets the custom endpoint for writing commands.
This change is incorrect. The sentence is talking about read/write commands.

2023-11-15 15:16 UTC, stoobie commented on components/Starknet/modules/cli/pages/starkli.adoc
> +Refer to xref:architecture_and_concepts:Network_Architecture/transaction-life-cycle.adoc[this] section for more information about the transaction lifecycle.
```suggestion
For more information, see xref:architecture_and_concepts:Network_Architecture/transaction-life-cycle.adoc[Transaction lifecycle].
```

2023-11-15 15:16 UTC, stoobie commented on components/Starknet/modules/quick_start/pages/declare_a_smart_contract.adoc
> +If either of the above commands fails, please visit xref:environment_setup.adoc[Setting up your environment].
```suggestion
If either of the above commands fails, see xref:environment_setup.adoc[Setting up your environment].
```

2023-11-15 15:16 UTC, stoobie commented on contributing_to_docs/doc_guidelines.adoc
> +* Avoid using markup in the code block. If you must use any markup in code blocks, see the Asciidoctor documentation on source blocks and substitutions:
```suggestion
* Avoid using markup in a code block. If you must use any markup in code blocks, see the Asciidoctor documentation on source blocks and substitutions:
```

2023-11-15 18:51 UTC, tudorpintea999 commented
hello @stoobie i didn t see the notification 3 days ago, check now please. Thanks !

2023-11-16 07:41 UTC, stoobie commented on components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts/contract-abi.adoc
> +You may not want to nest enums when serializing the event. For example, if you write an ERC-20 as a component, not a contract, that is pluggable anywhere, you might not want the contract to modify th
```suggestion
You might not want to nest enums when serializing the event. For example, if you write an ERC-20 as a component, not a contract, that is pluggable anywhere, you might not want the contract to modify the keys of known events such as `Transfer`.
```

2023-11-16 07:48 UTC, merged

2023-11-16 07:49 UTC, stoobie commented
Merged to new branch to generate preview before merging to dev.